### ISSUE TITLE
Proposed "metamacro" definitions.

### ISSUE THREAD

**Issue by MichaelHatherly** [MichaelHatherly/Docile.jl#106]
We've discussed issues surrounding the *behaviour* that `metamacro`s should have, ie. nesting, escaping, mutability of metadata stores, but not a concrete set of predefined `metamacro`s prodived by Docile out of the box.

This is a planning issue for which ones we should provide and what kind of behaviours they should have.

Some initial suggestions:

`!!get(<key>)`

Search the documented object's stored metadata, the module, and package for the symbol `<key>` and return it if found. Throw an error if not.

`!!set(<key>:<value>)`

Assign the string `<value>` to the documented object's metadata store under field `<key>`. Throw an error if it's already set? Or overwrite?

`!!include(<filename>)`

Splice in the contents of the file `<filename>` found relative to the source file where the `!!include` is called from. Throw an error when not found? Or warning, or splice in the invalid filepath?

`!!example(<code>)`

Take a self-contained code example, run it, and splice back formatted text containing the code followed by the output of the results from running the code.

`!!longform(<text>)`

Only display the contents when not at the REPL. Could contain additional `!!include(<filename>)` calls.

`!!summary(<text>)`

Short text to describe the behaviour of a documented object. Could issue a warning if too long. Use it as the text for the Lexicon index pages maybe.

**Comment by peter1000** [comment]
just to get me up-to-date: with your thinking

* general usage: !!set , !!get  for most cases
* others for special purpose.

> !!include is called from. Throw an error when not found? Or warning, or splice in the invalid filepath?

I think if one uses it explicit it is an error - but as we also want to gather all available info for as much pkg as possible maybe the best would be a: 

**splice in the invalid filepath? with an leading ERROR**

 or so that it is very clear something is missing. probably a long part otherwise they would not use an extra file.

**Comment by MichaelHatherly** [comment]
Good idea, so something like this for the resulting output?

```
...
ERROR: "!!include(<filename>)". File not found.
...
```

> !!set , !!get for most cases

> others for special purpose.

Yes, and yes. A lot can already be covered by `!!get` and `!!set` and of course additional package-specific ones can be written in a `.docile` file as well. So I doubt we'll need a huge amount of them.

**Comment by peter1000** [comment]
> !!set(<key>:<value>)
>
> Assign the string <value> to the documented object's metadata store under field <key>. Throw an error if it's already set? Or overwrite?

We discussed that before: I still think that overwriting such content could lead to a whole lot of undefined issues: example: 

```!!summary(This is the best Docile ever)```

Somehow it get's overwriten: getmeta[:summary] = "Throws an error"

Index page you have description: "Throws an error"

**Comment by peter1000** [comment]
>ERROR: "!!include(<filename>)". File not found.

I think !!get should maybe also just give a warning plus splice something similar into it.

Most of the time one downloads a julia package of other coders and if there is a small error it's difficult to fix for an outside user.

**Comment by MichaelHatherly** [comment]
> could lead to a whole lot of undefined issues

Definitely, it could. Though there *could* be valid reasons to want to mutate a field that we've not come across yet. Making the `ObjectIdDict` readonly would require wrapping it in an additional type and implementing methods on top of that, additional work and complexity.

``!!get`` errors / warning is much simpler to sort out and would definitely be a good thing.

> Most of the time one downloads a julia package of other coders and if there is a small error it's difficult to fix for an outside user.

Hopefully packagers will be using `Lexicon.doctest` soon to catch those kind of bugs ;)

**Comment by peter1000** [comment]
**!!section**

It would be nice if a `!!section` meta could be added which does not splice in anything at all. Because when one reads the doc it is already in the section it points to. 
If it is on an separate line: maybe the empty remaining line could be skipped too.

```julia
"""
test

!!section(Lexicon.md/Exported/Methods/1)
"""
```

OUT

```julia
"""
test

"""
```

**Comment by MichaelHatherly** [comment]
Isn't this already covered by ``!!set(section:Lexicon.md/Exported/Methods/1)``?

A metamacro can't affect anything outside of the brackets so chomping extra newlines can't be done so easily, but it's not really needed since Markdown doesn't care about multiple newlines anyway. Just treats them as a single paragraph break.

**Comment by peter1000** [comment]
> Isn't this already covered by !!set(section:Lexicon.md/Exported/Methods/1)?

It seems so: I misunderstood this because from a previous example I thought `!!set` will automatically also splice in the value. I think it would be good to have something which does both in one go too.

otherwise one has to write all the time a extra !!get which will make the general written text more unreadable just as a docstring or write still for most of them a extra "metamacro".

```julia
"""
!!set(author:Michael Hatherly)!!get(author)


text
"""
```

So, `!!set` does what I wanted `!!get` is also good. But there should be one combined one:
which is what I think will be used most of the time.

I will send an PR

**Comment by peter1000** [comment]
I don't have a concrete example but I thought maybe in the future a bool could be added: just to set a meta to true or false.

```
!!true(extra)
!!false(extra)
```
Or similar to set
```
!!true(extra:)
!!false(extra:)
```

just a thought.

**Comment by peter1000** [comment]
[!!href(text:url)](https://github.com/MichaelHatherly/Docile.jl/pull/110) Creates an link suitable for markdown format.

**Comment by MichaelHatherly** [comment]
> just to set a meta to true or false

Have you managed to come up with a use case?

**Comment by peter1000** [comment]
> Have you managed to come up with a use case?

**not yet** but I think it might have an application when we use the new things a bit more.
Like: `!!true(include_in_reference)`  Which one might overwrite somewhere with an option:

"To include all set: :unclude_all=true" or something along this lines. lets wait this was just an idea.

---

 I got stuck for a while with the `.docile` file - it did not work in the root of a package.

Finally I discovered that you put it in `Lexicon/src/.docile` I seem to have misunderstood that and thought it belongs into: `Lexicon/.docile`

I also re-signed up so I could join gitter. Don't like to give every 3rd party my email. so it's: https://github.com/peter1000-extern  on gitter.

**Comment by MichaelHatherly** [comment]
> Like: !!true(include_in_reference) Which one might overwrite somewhere with an option:
> 
> "To include all set: :unclude_all=true" or something along this lines. lets wait this was just an idea.

That sounds reasonable, but lets rather wait until we're further along with updating Lexicon before adding too many low-use metamacros.

On a related note, a `!!language(LANG: ...)` might be cool to have *at some point*. Conditionally display the contents `...` when the user's language matches `LANG`.

> I got stuck for a while with the `.docile` file - it did not work in the root of a package.

Given that Docile doesn't need to look at anything outside of `src` for docstrings I felt keeping the config there was best.

**Comment by peter1000** [comment]
> On a related note, a !!language(LANG: ...) might be cool to have at some point. Conditionally display the contents ... when the user's language matches LANG.

Not sure how much it would be used given the small julia community - but it is definitely a cool idea - quite in the footstamps of your own [comment](https://github.com/MichaelHatherly/Docile.jl/issues/112#issuecomment-101366250) **Let's not get ahead of ourselves ;)**

**Comment by MichaelHatherly** [comment]
> Let's not get ahead of ourselves ;)

Yeah, just a note for reminding me later really.

**Comment by MichaelHatherly** [comment]
Raw metamacros, without nesting, are now defined by `::META"a_raw_metamacro"raw`. Nesting is the default behaviour.

**Comment by peter1000** [comment]
that's great thanks. :+1:

**Comment by MichaelHatherly** [comment]
@peter, ``!!setget``'s name is bugging me slightly after using it for a while now. How does ``!!var`` or ``!!def`` sound to you as a replacement?

**Comment by MichaelHatherly** [comment]
Gone with ``!!var`` for the moment. 0ab9b8bcf002edb975c85943d82ee4cf7824046e

**Comment by peter1000** [comment]
Ok with me - I do not care so much about names and it's your package so nothing should bug you ;)  At the moment I also do noth think many will use that already but later on renaming such might be a pain.

**Comment by spencerlyon2** [comment]
Do we have the `!!example` metamacro yet? That one looked particularly awesome.

**Comment by MichaelHatherly** [comment]
> Do we have the ``!!example`` metamacro yet?

Not yet, that one kind of slipped my mind. It would definitely be nice to have. It's mostly just a question of what kind of output it should produce. Perhaps something simple like turning the contents of

```julia
"""
!!example(
<<code>>
)
"""
...
```

into

    **Example**

    ```julia
    <<code>>
    ```

    ```
    <<output>>
    ```

Also, when the code block has an error we could either throw the error and force the author to resolve it immediately or just display it as the resulting output.

It could also be worth allowing the author to pass some settings to ``!!example`` such as:

- whether to number each example in a docstring
- throw errors or embed then in the resulting output

```julia
"""
!!example((numbered, throwerrors)
<<code>>
)
"""
...
```

Not sure about that syntax though.

---

For the full list of what's been implemented so far you can check out ``src/Extensions/Extensions.jl`` and for any metamacros that are too package-specific to be included by default you can define then in a ``src/.docile`` config file. ``!!example`` is definitely worth adding to Docile though.

**Comment by peter1000** [comment]
> Also, when the code block has an error we could either throw the error and force the author to resolve it immediately or just display it as the resulting output.

An other thought would be instead of passing such option to each example to have some kind of global settings: `metadata throw example error` whatever the name would be.

PS: probably be the end of next week I will be back to do work on Lexicon.

**Comment by MichaelHatherly** [comment]
> some kind of global settings

Preferably a per-``ModuleData`` or per-``PackageData`` setting rather than truly ``global``.

> PS: probably be the end of next week I will be back to do work on Lexicon.

Thanks for the heads-up.

**Comment by MichaelHatherly** [comment]
Probably not relevant anymore given the work done on the `rewrite` branch.
