### ISSUE TITLE
Internal reference

### ISSUE THREAD

**Issue by peter1000** [MichaelHatherly/Docile.jl#112]
Now where we move so far: Internal reference might be easier. I will post here my thoughts.

**Comment by peter1000** [comment]
Previusly I added extra: Anchors above each obj output docstring which where calculated after all was written. This made internal reference nearly impossible. (with some work it would have been possible)

With the new excellent meta syntax system we might find a better solution.

---

IDEA:

We can know now exactly where an object will be output: requirement is that: `!!set(secion:Testing1.md/Exported/1)` is probably implemented on Lexicon side.

EXAMPLE TARGET:

```julia
module Testing1

"""
!!summary(Substracts `b` from `a`)

Function Author: !!setget(author:Hugo Boss)
Function License: !!setget(license:[GPL](http://www.gnu.org/copyleft/gpl.html))

!!set(secion:Testing1.md/Exported/1)
"""
function substract(a::Int, b::Int)
    return a - b
end

end #module
```

EXAMPLE LINK REF: something like this

```julia
module Testing2

"""
!!summary(Calulates the sum of the arguments)

Author: !!setget(author:Michael Hatherly)
License: !!setget(license:[MIT](https://github.com/MichaelHatherly/Lexicon.jl/blob/master/LICENSE.md))


See also: !!link(Testing1.substract:LinkText)

!!set(Testing2.md/Exported/1)
"""
function sum(a::Int, b::Int)
    return a + b
end


end # module
```

Bases on `!!link(Testing1.substract:LinkText)` we can get the meta: `Testing1.substract[:section]` and calculate any relative final link depending on the format.

?

**Comment by MichaelHatherly** [comment]
Yes, this sounds good.

**Comment by peter1000** [comment]
2 questions:

Should such be also handled within Lexicon or Docile?

`what would be the best to refer to an obj` I'm a bit unsure how this `!!link(Testing1.substract:LinkText)`

`Testing1.substract` within the text string could be best implemented?

**Comment by peter1000** [comment]
I saw your **Allow for Base documentation.** now an related thought: if we could auto add to  the `Base docstrings` a section meta one could reference them within the standalone documentation.

**Comment by MichaelHatherly** [comment]
> Should such be also handled within Lexicon or Docile?

Hopefully all on the Lexicon side of things though there are some concerns:

To be able to pick up all reference names and locations of reference usage we might need some kind of two-pass to do things properly. Also realise that the *order* or docstring parsing is undefined since we are iterating over an unordered `ObjectIdDict` of raw docstrings.

**Comment by MichaelHatherly** [comment]
> I saw your Allow for Base documentation. now an related thought: if we could auto add to the Base docstrings a section meta one could reference them within the standalone documentation.

Let's not get ahead of ourselves ;)

**Comment by peter1000** [comment]
>Let's not get ahead of ourselves ;)

I have faith: just think about that: [ peter1000 commented 27 days ago ] opened `Extract for ALL Pkg documentation` #71

> Also realise that the order or docstring parsing is undefined

Yeh you are probably right - need first to suck in all metas and than splice them out in case of links

**Comment by MichaelHatherly** [comment]
> need first to suck in all metas and than splice them out in case of links

We *could* use a `!!ref` of some kind to splice in a special looking markdown link that we then look for in the Markdown ASTs that are generated by `parsedocs` and rewrite them then, but it's still a little tricky.

> I have faith: just think about that: [ peter1000 commented 27 days ago ] opened Extract for ALL Pkg documentation #71

I've not tried it yet, but calling `using` for *every* available package and then letting Docile parse them might be an interesting experiment...

**Comment by MichaelHatherly** [comment]
Probably not relevant anymore given the work done on the `rewrite` branch.
