### ISSUE TITLE
possible bug: not normalized path

### ISSUE THREAD

**Issue by peter1000** [MichaelHatherly/Docile.jl#113]
Not sure what to call the heading. I'm also not sure if that has to do with julia or Docile.
but might be interesting to you as info in any case:

I have an module file  in an other directory. This works fine

```
require("../Testing1.jl")

import Docile: Formats, Cache, Utilities
using Compat
raw_ = Docile.Cache.getraw(Testing1)
println("\nraw_: ", raw_)

```

If I do it like this: Also OK

```
modulepath = normpath(joinpath(dirname(@__FILE__), "..", "Testing1.jl"))
require(modulepath)

import Docile: Formats, Cache, Utilities
using Compat
raw_ = Docile.Cache.getraw(Testing1)
println("\nraw_: ", raw_)
```

But if I do not normalize the path: there is a problem ?

```
modulepath = joinpath(dirname(@__FILE__), "..", "Testing1.jl")
require(modulepath)


import Docile: Formats, Cache, Utilities
using Compat
raw_ = Docile.Cache.getraw(Testing1)
println("\nraw_: ", raw_)

```

OUTPUT

```
Docile: updating package list…
Docile: caching 'Testing1'…
 - Testing1 ✓

raw_: ObjectIdDict()

```

took me a while to find that out ;)

Anyway do you see something obvious or have any ideas what it could be?
In any case it's maybe useful you are aware otherwise you might waist also some time on it wondering.

**Comment by peter1000** [comment]
I guess we where a bit lucky with our test ;)

[here](https://github.com/MichaelHatherly/Docile.jl/blob/master/test/Formats/facts.jl#L1)
```
require(joinpath(dirname(@__FILE__), "MetadataSyntax.jl"))
require(joinpath(dirname(@__FILE__), "UndefinedMetaMacro.jl"))
require(joinpath(dirname(@__FILE__), "UnmatchedBrackets.jl"))
```

[here](https://github.com/MichaelHatherly/Docile.jl/blob/master/test/Collector/facts.jl)

```
require(joinpath(dirname(@__FILE__), "PlainDocs.jl"))
```

**Comment by peter1000** [comment]
Something more: seems julia works ok

```
modulepath = joinpath(dirname(@__FILE__), "..", "Testing1.jl")
require(modulepath)

x=Testing1.substract(1,5)
println(x)

-4
```

**Comment by MichaelHatherly** [comment]
I wasn't able to recreate your error, but I've pushed some path normalisation fixes, f05c460b400fdcfc6fc13eab37c114e3e710ec12, that might help.

If it's still giving problems could you show the contents of the module and the whole folder structure, thanks.

**Comment by MichaelHatherly** [comment]
> I wasn't able to recreate your error

Scratch that, I wasn't trying with docstrings for `Method` objects, I only had a `Module` docstring. f05c460b400fdcfc6fc13eab37c114e3e710ec12 does indeed seem to fix it.

Problem was due to the path comparison code [here](https://github.com/MichaelHatherly/Docile.jl/blob/f05c460b400fdcfc6fc13eab37c114e3e710ec12/src/Runner/lookup.jl#L16) comparing normalised to not normalised versions of the same path and giving `false` as the answer.

**Comment by peter1000** [comment]
seems to work: but still funny 'cause [abspath](https://github.com/MichaelHatherly/Docile.jl/commit/f05c460b400fdcfc6fc13eab37c114e3e710ec12#diff-cc6c83e0c8777a807ed9f63e7c1c6402L49) should also normize the path anyhow when I looked at it the last time?

[julia src](https://github.com/JuliaLang/julia/blob/master/base/path.jl#L108)

```
abspath(a::AbstractString) = normpath(isabspath(a) ? a : joinpath(pwd(),a))
abspath(a::AbstractString, b::AbstractString...) = abspath(joinpath(a,b...))
```
