### ISSUE TITLE
using own compiled julia:  Error Cache Base and it's submodules.

### ISSUE THREAD

**Issue by peter1000** [MichaelHatherly/Docile.jl#122]
Just to let you know - I do not install julia but only recompile it: in which case `julia/usr/share/julia/base` is empty.

running the tests errors

```julia
79 facts verified.
Base
     - Cache Base and it's submodules.
Docile: updating package list…
  Error   :: (line:-1) :: Cache Base and it's submodules.
    isempty(Docile.Cache.getparsed(Base)) => true
SystemError: unable to read directory /0_JULIA_COMPILED_0/git_julia/usr/share/julia/base: No such file or directory
 in readdir at ./file.jl:246

```

**Comment by MichaelHatherly** [comment]
You might have broken the symlink then. The directory should just link to `/base`. Works for me and has been working on the CI. Perhaps you copied the `git_julia` folder from somewhere else?

**Comment by peter1000** [comment]
While I'm away I will recomplie from scratch and update here later.

**Comment by MichaelHatherly** [comment]
> recomplie from scratch

:(

Do you have

```make
override OPENBLAS_DYNAMIC_ARCH = 0
```

in your `Make.user` file? Cuts down compile times significantly.

**Comment by peter1000** [comment]
you where right: it places the link there

Thanks
