### ISSUE TITLE
register Formatter ?

### ISSUE THREAD

**Issue by peter1000** [MichaelHatherly/Docile.jl#128]
[DOCS](https://github.com/MichaelHatherly/Docile.jl/blob/master/src/Formats/formatting.jl#L7-L19)

Example:
```
import Docile.Formats, Markdown
const (fmt, md) = (Docile.Formats, Markdown)

immutable MarkdownFormatter <: fmt.AbstractFormatter end

fmt.parsedocs(::fmt.Format{MarkdownFormatter}, raw, mod, obj) = md.parse(raw)
```

When registering a package the format is then provided to PackageData.

---

It seems that this is not picked up: also your other examples suggests that one needs to set the [:format] meta.

* [tests](https://github.com/MichaelHatherly/Docile.jl/blob/master/test/Formats/facts.jl#L9)

`Cache.getmeta(MetadataSyntax)[:format] = Formats.PlaintextFormatter`

* [.docile](https://github.com/MichaelHatherly/Docile.jl/blob/master/src/Collector/utilities.jl#L318-L320)

```julia
Dict(
        :format => MyCustomFormatter,
        # ...
    )
```

* [extractor](https://github.com/MichaelHatherly/Docile.jl/blob/master/src/Cache/utilities.jl#L47-L54)

```julia
function extractor!(raw::AbstractString, m::Module, obj)
    str    = Formats.extractmeta!(raw, m, obj)
    format = findmeta(m, obj, :format)
    Formats.parsedocs(Formats.Format{format}(), str, m, obj)
end
```
* [comment example](https://github.com/MichaelHatherly/Docile.jl/issues/102#issuecomment-100638505)

```julia
Formats.parsedocs(::Formats.Format{MarkdownFormatter}, raw, mod, obj) =
    Base.Markdown.parse(raw)

Dict(
    :format => MarkdownFormatter
)
```

---

Question: did I miss something or does one have to set the meta [:format] do as in the examples?

What would be the best why to set it globally: ? `.docile`?  if such is required maybe it should be mentioned at the top [DOCS](https://github.com/MichaelHatherly/Docile.jl/blob/master/src/Formats/formatting.jl#L7-L19)

**Comment by MichaelHatherly** [comment]
We're still using ``Legacy.parsedocs``, which is not the same function as ``Formats.parsedocs``.

I'll add the needed definitions later today if possible.

**Comment by MichaelHatherly** [comment]
Closed by 7fa03357a1d9f7d74904264f3f91a3f21f3589ea.

**Comment by peter1000** [comment]
```julia
workspace()
import Docile.Formats
const (fmt, md) = (Docile.Formats, Markdown)
fmt.parsedocs(::fmt.Format{fmt.MarkdownFormatter}, raw, mod, obj) = md.parse(raw)
    

import Docile: Cache
objects = Cache.objects(Cache);
parsed =  Cache.getparsed(Cache, objects[5])
typeof(parsed)
```

```
julia> typeof(parsed)
Base.Markdown.MD

```

seems to work now: but from you commit I thought it should be default? [ Add MarkdownFormatter type. Make it default.](https://github.com/MichaelHatherly/Docile.jl/commit/7fa03357a1d9f7d74904264f3f91a3f21f3589ea)

```julia
workspace()
import Docile: Cache
objects = Cache.objects(Cache);
Cache.getmeta(Cache, objects[5])

```

```
julia> typeof(parsed)
ASCIIString
```

Did I misinterpret the commit title?

**Comment by MichaelHatherly** [comment]
The actual definition of ``parsedocs`` that parses strings to markdown must be defined in Lexicon so we don't have to import all of `Markdown` into Docile.
