### ISSUE TITLE
User experience: get metadata

### ISSUE THREAD

**Issue by peter1000** [MichaelHatherly/Docile.jl#131]
Just thought from a user experience the way of how to get `metadata` is a bit inconsistence.

[function findmeta](https://github.com/MichaelHatherly/Docile.jl/blob/master/src/Cache/utilities.jl#L10-L30)

* Package's metadata: `meta = getpackage(root).metadata`
* Module's metadata: `meta = getmodule(m).metadata`
* object's metadata: `meta = getmeta(m, obj)`

  * `getmeta(obj).metadata`

or:

* Package's metadata: `meta = getpackage_meta(root)`
* Module's metadata: `meta = getmodule_meta(m)`
* object's metadata: `meta = getobj_meta(obj)`

Which fits in to my question about [obj meta](https://github.com/MichaelHatherly/Lexicon.jl/pull/111#issuecomment-105482347)

Just a thought maybe there is a way to make it for all 3 levels the same? Not necessarily my name suggestion though ;)

**Comment by MichaelHatherly** [comment]
The difference is that ``getmeta`` has to do some work to extract the metadata from a docstring, whereas ``ModuleData`` and ``PackageData`` objects don't.

I'm not a fan of the underscored names ``getpackage_meta``, etc. as public method names. We should be using multiple dispatch to simplify it a bit. Perhaps:

```jl
getmeta(::PackageData)
getmeta(::ModuleData)
getmeta(::Module)
getmeta(::Module, ::Any)
```

How's that sound to you?

**Comment by peter1000** [comment]
> I'm not a fan of the underscored names 

I know ;) that's why I wrote `Not necessarily my name suggestion though`

yep your suggestion looks from a user perspective more consistent than the current implementation

**Comment by MichaelHatherly** [comment]
Generic ``getmeta`` added here https://github.com/MichaelHatherly/Docile.jl/commit/9e930d821ab3ba7618dd8fa87a96d504a3cf6b42#diff-f09e69cbce12e451a81ba8365fb18c85R212.
