### ISSUE TITLE
Documentation of the package/module name

### ISSUE THREAD

**Issue by julian-gehring** [MichaelHatherly/Docile.jl#134]
Let's assume we have a very simple package, called `Minimal.jl` (https://github.com/julian-gehring/Minimal.jl), which only consists of:

```julia
module Minimal

"""
Doc for the package 'Minimal'
"""
Minimal

using Docile
@document

end
```

My goal is to have a docstring bound to the package name, i.e. that `?Minimal` will print the documentation of the package.  http://docilejl.readthedocs.org/en/latest/syntax/ uses the same synthax for documenting a module.

```julia
using Lexicon
using Minimal

?Minimal
```

gives

```
INFO: Loading help data...
Symbol not found. Falling back on apropos search ...
Base.gcdx(x, y)
Base.print(x)

Docile: updating package list…
Docile: caching 'Docile'…
 - Docile.Interface  ✓
 - Docile.Cache      ✓
 - Docile.Legacy     ✓
 - Docile.Utilities  ✓
 - Docile.Collector  ✓
 - Docile.Extensions ✓
 - Docile            ✓
 - Docile.Formats    ✓
 - Docile.Runner     ✓
Docile: caching 'Lexicon'…
 - Lexicon ✓
Docile: caching 'Compat'…
 - Compat       ✓
 - Compat.Libdl ✓
 - Compat.Libc  ✓
Docile: caching 'Minimal'…
 - Minimal ✓

[module]

Minimal.Minimal

  Doc for the package 'Minimal'

 Details:

	source: (6,"/home/julian/.julia/v0.3/Minimal/src/Minimal.jl")
```

So it works somehow, but seems to use an apropos search instead of finding the docstring of the module directly. Is this the expected behavior?

**Comment by MichaelHatherly** [comment]
The reason you're seeing apropos here is that Lexicon has to add additional code to base help [here](https://github.com/MichaelHatherly/Lexicon.jl/blob/bde88f7b83ce5598544df54e6da9b4001542ac7d/src/query.jl#L219-L228).

The help system in base can't find any objects matching ``Minimal`` so it falls back on string search. After that Lexicon does a search for the ``Module`` object not the string.

Hope that helps.

**Comment by MichaelHatherly** [comment]
FYI:

```jl
using Docile
@document
```

isn't needed anymore if you're just using plain docstrings. Docile will pick up docstrings in any loaded module now.

**Comment by julian-gehring** [comment]
Thanks, that makes things clearer.
