### ISSUE TITLE
findmeta: maybe accept a default instead of error

### ISSUE THREAD

**Issue by peter1000** [MichaelHatherly/Docile.jl#136]
https://github.com/MichaelHatherly/Docile.jl/blob/master/src/Cache/interface.jl#L68

I thought maybe `findmeta` should accept a default instead of throwing an error.

```julia
findmeta(m::Module, obj, field::Symbol, default = :notfound)
```

The other thing is I though `key` would be a better name instead of `field` as it searches the dictionary doesn't it? and the actual function uses `key`  

```julia
function findmeta(cache::GlobalCache, m::Module, obj, key::Symbol)
```

A default would make it also more in line with what I had in mind for Lexicon: [getconfig](https://github.com/peter1000/Lexicon.jl/blob/diverse_commits/src/Elements/utilities.jl#L3)

```julia
function getconfig(n::Node, key::Symbol, default = :notfound)
```

just a though

**Comment by MichaelHatherly** [comment]
Yes, I've been thinking about doing that. I'll sort it out later today if I have time.

**Comment by MichaelHatherly** [comment]
7cdc941e09cdbf6d306181aa2e54de25c67b3688 makes ``findmeta`` return a ``Nullable{T}`` object that can then be unwrapped. This makes it a bit more type stable hopefully. It also puts the resposibilty of the caller to check they've got a value back.

**Comment by peter1000** [comment]
I guess than `getconfig` should do the same?

Eventhough I do not really understand the whole purpose - I can try it based on your implementation.

Or should I better keep the default:  [getconfig](https://github.com/peter1000/Lexicon.jl/blob/diverse_commits/src/Elements/utilities.jl#L3)

**Comment by MichaelHatherly** [comment]
> Eventhough I do not really understand the whole purpose

The default value is the linked code is ``:notfound``, a ``Symbol``. If the value returned from the config is not a ``Symbol`` then the method is not type stable.

**Comment by MichaelHatherly** [comment]
> I guess than ``getconfig`` should do the same?

If you'd like to, yes. Might work out nicely.

**Comment by peter1000** [comment]
Seems your documentation is not clear after the change: https://github.com/MichaelHatherly/Docile.jl/blob/master/src/Cache/interface.jl#L67

you still refer ti `field` even there is no argument with that name

**Comment by MichaelHatherly** [comment]
Oh, thanks! Would be a nice feature for metamacros, a ``!!arg(field)`` that checks whether you actually have an argument called ``field`` and splices in "\`\`field\`\`" into its place.

**Comment by peter1000** [comment]
> Would be a nice feature for metamacros, a !!arg(field) that checks whether you actually have an argument called field and splices in "``field``" into its place.

maybe - the question would be what does it do if no field is found ?

Still think a 2 pass run for meta syntax might make sense.

**Comment by peter1000** [comment]
Seems one needs additional converts for the `Nullable`

```
MethodError: `convert` has no method matching convert(::Type{Nullable{UTF8String}}, ::ASCIIString)
This may have arisen from a call to the constructor Nullable{UTF8String}(...),
```

No problem just wanted to let you know.

**Comment by MichaelHatherly** [comment]
> Seems one needs additional converts for the ``Nullable``

Is this an error coming from the Docile codebase? Or just the behaviour of ``Nullable`` in general?

**Comment by peter1000** [comment]
It was in Lexicon when I did something like: `findconfig(n, :title, UTF8String)` but I had forgotten that the title is only later converted to `UTF8String` so at the point of the call it was a `ASCIIString`.

I changed it to: ``findconfig(n, :title, AbstractString)` and it runs fine. But maybe something to look out - on the otherhand I guess this is the whole purpose of type stability isn't it ;)

**Comment by MichaelHatherly** [comment]
We could put in a ``convert`` call perhaps. I'll look at that later this evening.

**Comment by MichaelHatherly** [comment]
1ea0a71f4a2ded1ccda0b5716a09050175a8e93e adds a ``convert`` call to ``findmeta``.
