### ISSUE TITLE
Modules without a newline after "end" are not parsed

### ISSUE THREAD

**Issue by AndrewGibb** [MichaelHatherly/Docile.jl#137]
Given the module-defining file MyDocTest.jl:
###
module MyDocTest
using Docile
"MyDocTest tests docs."
MyDocTest
end # module
###
Loading Docile and Lexicon, and querying the defined documentation:
```Julia
using Docile, Lexicon
using MyDocTest
?MyDocTest
```
produces no information about MyDocTest. If the file has a newline added at the end, like so:
###
module MyDocTest
using Docile
"MyDocTest tests docs."
MyDocTest
end # module

###
Then `?MyDocTest` produces the expected result. 

Edits: Nice markdown parsing hides the effect I'm trying to highlight. Fugly ### syntax denotes start and end of files.

**Comment by MichaelHatherly** [comment]
This is quite odd. Could you provide the output of ``versioninfo()`` and the versions of both Docile and Lexicon (found using ``Pkg.status()``). The newline difference doesn't appear to be making a difference for me, perhaps platform differences.

**Comment by AndrewGibb** [comment]
julia> versioninfo()
Julia Version 0.3.10-pre+4
Commit c8804e8 (2015-06-04 13:19 UTC)
Platform Info:
  System: Darwin (x86_64-apple-darwin13.4.0)
  CPU: Intel(R) Core(TM) i7-4850HQ CPU @ 2.30GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Haswell)
  LAPACK: libopenblas
  LIBM: libopenlibm
  LLVM: libLLVM-3.3

Docile: 0.5.4
Lexicon: 0.1.10

**Comment by MichaelHatherly** [comment]
I guess just appending ``\n`` to the end of each file before parsing would work. I'll push that change a little later and if it works for you I'll tag a new version.

**Comment by MichaelHatherly** [comment]
@AndrewGibb aa5eafe4bbc177d8eae1219c9299a0d83bef94d6 should resolve this issue. If you have a chance to confirm that would be great, thanks.

**Comment by MichaelHatherly** [comment]
If it's not fixed then let me know and I'll reopen this.

**Comment by AndrewGibb** [comment]
@MichaelHatherly It is fixed. Thanks.

**Comment by MichaelHatherly** [comment]
Great!
