### ISSUE TITLE
For consistencey could we add :codesource to Aside

### ISSUE THREAD

**Issue by peter1000** [MichaelHatherly/Docile.jl#138]
Docile.Collector.Aside
ERROR: LoadError: KeyError: codesource not found

being the same as the opening `[`

**Comment by MichaelHatherly** [comment]
Their is no code related to an ``Aside`` so this doesn't really make such sense to store. Just check whether it's an ``Aside`` and don't display codesource in that case?

**Comment by MichaelHatherly** [comment]
Just to go a bit further: my thinking is that ``Aside`` will be used mostly for "internals" documentation, kind of like a map to the source code and would be generated in a separate section/page of the resulting manual.
