### ISSUE TITLE
Feature Request: Give all possible type information.

### ISSUE THREAD

**Issue by Ismael-VC** [MichaelHatherly/Docile.jl#141]
Right now we either have this:

``` julia
julia> # exercise the codepath in searchsorted* methods for ranges that check for zero step range

julia> immutable ConstantRange{T} <: Range{T}
          val::T
          len::Int
       end

help?> ConstantRange
search: ConstantRange

DataType   : ConstantRange{T}
  supertype: Range{T}
  fields   : [:val,:len]
```

Or this:

``` julia
julia> @doc """
       # `ConstantRange`

       Exercise the codepath in `searchsorted*` methods for
       ranges that check for **zero** step range.
       """ ->
       immutable ConstantRange{T} <: Range{T}
          val::T
          len::Int
       end

help?> ConstantRange
search: ConstantRange

     ConstantRange


  Exercise the codepath in searchsorted* methods for ranges that check for zero step range.
```

It would be nice if we could have both of these type definitions help info by default:

``` julia
julia> @doc """
       # `ConstantRange`

       Exercise the codepath in `searchsorted*` methods for
       ranges that check for **zero** step range.
       """ ->
       immutable ConstantRange{T} <: Range{T}
          val::T
          len::Int
       end

help?> ConstantRange
search: ConstantRange

     ConstantRange


  Exercise the codepath in searchsorted* methods for ranges that check for zero step range.


DataType   : ConstantRange{T}
  supertype: Range{T}
  fields   : [:val,:len]
```

**Comment by MichaelHatherly** [comment]
Yes, we can definitely add more information automatically. Though we shouldn't completely overload a user with too many details all at once.

This is probably most relevant to Lexicon though, particularly the 0.2 planning issue https://github.com/MichaelHatherly/Lexicon.jl/issues/109 and the display planning issue https://github.com/MichaelHatherly/Lexicon.jl/issues/118.

Docile already collects all the information necessary, it's just a matter displaying it nicely.

---

For documenting things in base people have been using bare docstrings in places, which Docile can already handle:

```
julia> import Lexicon

help?> Base.checkstring

checkstring (generic function with 3 methods)
Docile: updating package list...
Docile: caching 73 modules from 'Base'.

[function]

Base.checkstring

  Validates and calculates number of characters in a UTF-8,UTF-16 or UTF-32
  encoded vector/string
  ...
```

I'm not sure what the policy is currently though, whether to using ``@doc`` or bare docstrings.

**Comment by Ismael-VC** [comment]
That is awesome! I agree that overloading the user is not the way to go, but it would be useful to have both API and implementation details, just not too much of both at the same time:

> *Virtue lies in the Middle Way*
