### ISSUE TITLE
unable to precompile Docile Julia Version 0.4.0-dev+5860

### ISSUE THREAD

**Issue by steven-varga** [MichaelHatherly/Docile.jl#144]
While all test passes, and the package is functional the precompile process stops with the following error:

 LoadError(at "sysimg.jl" line 331: LoadError(at "/usr/local/share/julia/base/userimg.jl" line 10: LoadError(at "/home/steven/.julia/v0.4/Docile/src/Docile.jl" line 42: LoadError(at "/home/steven/.julia/v0.4/Docile/src/Utilities.jl" line 277: UndefVarError(var=:JULIA_HOME)))))
rec_backtrace at /usr/local/bin/../lib/julia/libjulia.so (unknown line)
jl_throw at /usr/local/bin/../lib/julia/libjulia.so (unknown line)
jl_undefined_var_error at /usr/local/bin/../lib/julia/libjulia.so (unknown line)

Julia Version 0.4.0-dev+5860
Commit 7fa43ed (2015-07-08 20:57 UTC)
Platform Info:
  System: Linux (x86_64-linux-gnu)
  CPU: Intel(R) Core(TM) i7-3667U CPU @ 2.00GHz
  WORD_SIZE: 64
  BLAS: libmkl_rt
  LAPACK: libmkl_rt
  LIBM: libimf
  LLVM: libLLVM-3.3

**Comment by MichaelHatherly** [comment]
Looks like ``JULIA_HOME`` isn't defined that early in the build process. Can you try this diff:

```diff
diff --git a/src/Utilities.jl b/src/Utilities.jl
index 91de11a..89e5782 100644
--- a/src/Utilities.jl
+++ b/src/Utilities.jl
@@ -99,12 +99,12 @@ issymbol(::Any)    = false
 """
 Path to Julia's base source code.
 """
-const BASE = abspath(joinpath(JULIA_HOME, "..", "share", "julia", "base"))
+basepath() = abspath(joinpath(JULIA_HOME, "..", "share", "julia", "base"))
 
 """
 Convert a path to absolute. Relative paths are guessed to be from Julia ``/base``.
 """
-expandpath(path) = normpath(isabspath(path) ? path : joinpath(BASE, path))
+expandpath(path) = normpath(isabspath(path) ? path : joinpath(basepath(), path))
 
 # Module initialization. #
 ```

and see if it compiles alright? Are you directly compiling Docile, or is it just a dependency for another package?

**Comment by steven-varga** [comment]
Thank you for your super quick reply!
I am compiling it directly; however it was Gadfly, DataFrames which failed because of this.  The patch worked, now Docile (and the rest of the chain)  compiles; getting out of memory error which maybe completely unrelated

**Comment by MichaelHatherly** [comment]
> getting out of memory error which maybe completely unrelated

With just ``require("Gadfly")`` is the ``userimg.jl`` file compiling the image is using ~850MB according to ``htop``. It does complete fine, eventually, for me though and appears to work, so I'd assume it's not going to be directly related to Docile.

> now Docile (and the rest of the chain) compiles

I'll tag a new Docile release shortly with this patch.

**Comment by steven-varga** [comment]
OK...

although for your information I tried the only Gadfly, then removing the rest and compiling it with only Docile
am still getting this message at startup:
Docile: upgrading cache to 0.0.2.
Warning: error initializing module Utilities:
OutOfMemoryError()
               _
Will investigate further; I am uncertain if this is related to Docile; and certain that not related to this problem. Before you providing the patch I replaced the JULIA_HOME with the right path and that worked. Then I removed Docile, reinstalled, checked out master, and patched it with your code. Now I am having this issue.

Will investigate further and get back to you,
best 
steve

**Comment by MichaelHatherly** [comment]
Looks as though it's having trouble creating the cache directory on first initialisation of Docile. If you run Docile once prior to compiling it and then compile after that does it still throw an ``OutOfMemoryError``?

**Comment by MichaelHatherly** [comment]
The following patch appears to fix the ``OutOfMemoryError``:

```diff
diff --git a/src/Utilities.jl b/src/Utilities.jl
index 89e5782..da5a969 100644
--- a/src/Utilities.jl
+++ b/src/Utilities.jl
@@ -55,6 +55,7 @@ Retrieve the ``Expr`` object from a Julia source file ``file``.
 Caches the expression based on it's file name and ``mtime`` value.
 """
 function parsefile(file::AbstractString)
+    __init_cache__()
     cached = path_id(file)
     if isfile(cached)
         open(deserialize, cached)
@@ -106,11 +107,4 @@ Convert a path to absolute. Relative paths are guessed to be from Julia ``/base`
 """
 expandpath(path) = normpath(isabspath(path) ? path : joinpath(basepath(), path))
 
-# Module initialization. #
-
-function __init__()
-    # Clear out old versions of the expression cache.
-    __init_cache__()
-end
-
 end
```

To test you'll need to delete ``Docile/cache/0.0.2`` folder manually or uninstall and reinstall Docile first.

At the REPL the following should work rather than giving the error:

```
julia> Docile.Cache.getraw(Docile)
Docile: updating package list...
Docile: upgrading cache to 0.0.2.
Docile: caching 9 modules from 'Docile'.
ObjectIdDict with 1 entry:
...
```

**Comment by steven-varga** [comment]
Thank you for the fix!  I checked out the latest Docile with the new commits then followed your instructions,   including:  Docile.Cache.getraw(Docile); then pre-compiled Gadfly and now it works like a charm.
best,
steve

**Comment by MichaelHatherly** [comment]
New tagged version in https://github.com/JuliaLang/METADATA.jl/pull/2874. Thanks for your help finding this bug.
