### ISSUE TITLE
precompilation error in Docile with julia v0.4

### ISSUE THREAD

**Issue by TransGirlCodes** [MichaelHatherly/Docile.jl#169]
Hi,

When I try to do `using Gadfly` on julia v0.4 I'm getting a precompliation error involving Docile:

```
julia> using Gadfly
INFO: Recompiling stale cache file /Users/bward/.julia/lib/v0.4/Gadfly.ji for module Gadfly.
WARNING: Module Docile uuid did not match cache file
  This is likely because module Docile does not support  precompilation but is imported by a module that does.
WARNING: deserialization checks failed while attempting to load cache from /Users/bward/.julia/lib/v0.4/Gadfly.ji
INFO: Precompiling module Gadfly...
INFO: Recompiling stale cache file /Users/bward/.julia/lib/v0.4/Gadfly.ji for module Gadfly.
WARNING: Module Docile uuid did not match cache file
  This is likely because module Docile does not support  precompilation but is imported by a module that does.
ERROR: __precompile__(true) but require failed to create a precompiled cache file
 in require at ./loading.jl:268
```

**Comment by TransGirlCodes** [comment]
Julia version is `Version 0.4.6-pre+34` I think that's more recent than `v"0.4.0-dev+6521"`, but not 100% sure.

**Comment by MichaelHatherly** [comment]
It's supported precompilation up until now fine as far as I know, can you delete all the cached files in `.julia/lib/v0.4` and see if it still happens?

**Comment by TransGirlCodes** [comment]
Yep I'll check, first I gotta wait for a new julia compilation, I wondered if I'd messed something up so I `rm -rf`'d the folder and am installing again.

**Comment by MichaelHatherly** [comment]
Yeah, I've seen these kind of errors before, but typically deleting the cache has work things out... hopefully that's the case here too.

**Comment by TransGirlCodes** [comment]
Your suggestion works! Thanks @MichaelHatherly
