### ISSUE TITLE
Use md"...." for markdown comments?

### ISSUE THREAD

**Issue by stevengj** [MichaelHatherly/Docile.jl#29]
Using an explicit prefix, via a string macro, has two advantages:

* String macros don't require escaping.   With plain strings, it will be awkward to document usage or code examples that involve `$` or `\n` etcetera.

* Being explicit about the formatting clears the path for other formats in the future.

The second point is more of a tradeoff, I suppose, but typing two extra characters seems a small price to pay.   The first point is extremely compelling to me.

("..." strings could default to text/plain, or even be disallowed.)

**Comment by MichaelHatherly** [comment]
Closed, since both base and Docile have implemented.
