### ISSUE TITLE
Methods sharing a single docstring

### ISSUE THREAD

**Issue by timholy** [MichaelHatherly/Docile.jl#38]
Suppose I have small variants of a function. I'm not sure that this is really consistent with the design of Docile/Lexicon, but just suppose I'd like to co-document them as a way of increasing awareness of these alternate syntaxes. (You see a lot of this with Matlab's documentation, e.g., http://www.mathworks.com/help/matlab/ref/linspace.html?refresh=true.) I can achieve an effect like that at the cost of duplicate entries that crop up in `query` searches. For example (for brevity, I'm truncating the obvious stuff):
```julia

import Base: push!

type MyObject end

str = """
    push!(MyObject, (a,b))
    push!(MyObject, a, b)

Add a pair to a MyObject queue.
"""

@doc "$str" ->
push!(obj::MyObject, a, b) = nothing

@doc "$str" ->
push!(obj::MyObject, t::NTuple{2}) = nothing
```
But now `query("push!")` will show what are essentially duplicates (the method signatures will of course be different).

Any thoughts on whether there is a better way? Or should I just not do this? :smile:

There will be a related issue over at Lexicon shortly.

**Comment by MichaelHatherly** [comment]
@timholy, bit belated, but this has been added in 6a7d5513f229c3068d778886577b2b15579c70a7 with the syntax (in this particular case):

```julia
"Add a pair to a MyObject queue."
(push!, MyObject, Any...)
```

using the new docstring syntax I'm working on.
