### ISSUE TITLE
Functions with optional arguments

### ISSUE THREAD

**Issue by dpo** [MichaelHatherly/Docile.jl#49]
If I document a function of the form
````
function f(x; y=0)
  # ...
end
````
the optional argument `y` doesn't appear in the documentation. Is there an option to `@doc` to activate the documentation of optional arguments? I'm using the stable version. Apologies if this is already in `master`.

Thanks!

**Comment by MichaelHatherly** [comment]
Hi @dpo, we could capture the ``Expr(:parameters, ...)`` object during ``@doc`` expansion, though it might be possible to also inspect either the ``Function`` or ``Method`` object for that information during runtime. It would be a great feature to have though &mdash; thanks for the suggestion.

**Comment by dpo** [comment]
Many thanks. I'm enjoying `Docile`!

**Comment by MichaelHatherly** [comment]
Glad to hear that!

**Comment by MichaelHatherly** [comment]
Closing in favour of https://github.com/MichaelHatherly/Lexicon.jl/issues/19.
