### ISSUE TITLE
Multiple constructors for a type

### ISSUE THREAD

**Issue by dpo** [MichaelHatherly/Docile.jl#50]
When a type has multiple constructors, is there a way to gather them all together with the type in the generated documentation instead of having them listed with the rest of the methods?

**Comment by MichaelHatherly** [comment]
Not at the moment. This should just involve some changes to the Lexicon.jl package probably. I'm currently adding support for inner constructors as well that should be ready relatively soon, so I'll see how this change looks with those changes as well.

**Comment by dpo** [comment]
Just a quick note to add that #49 and #50 can combine. If I document a constructor with only optional arguments, it doesn't appear in the HTML documentation at all.

**Comment by MichaelHatherly** [comment]
Could you provide an example where this happens for me to investigate further with?

**Comment by dpo** [comment]
Here are
* [the original (inner) constructor](https://github.com/dpo/MUMPS.jl/blob/master/src/mumps.jl#L106)
* [the alternative constructor](https://github.com/dpo/MUMPS.jl/blob/master/src/mumps.jl#L137) that only has keyword arguments.

And [here](http://dpo.github.io/MUMPS.jl/MUMPS.html) is the documentation generated.

Neither constructor ends up in the documentation. For the first one, you mentioned that inner constructors are work in progress. But for the second one, it seems related to optional arguments.

**Comment by MichaelHatherly** [comment]
Cool, thanks. I'm just trying to install MUMPS.jl to see if I can narrow down what's happening.

**Comment by MichaelHatherly** [comment]
Do the constructors appear in the REPL if you search for them there?

**Comment by dpo** [comment]
If I say `query(Mumps)`, I only get documentation on the type, not the constructors.
````
julia> query(Mumps)

[type]

 > MUMPS.Mumps
Abstract type representing a factorization with MUMPS. All constructor arguments are optional. By default a general unsymmetric matrix will be analyzed/factorized with default integer and real parameters
 Details:

	source: (91,"/Users/dpo/.julia/v0.3/MUMPS/src/MUMPS.jl")
````

**Comment by MichaelHatherly** [comment]
Try `query(Mumps, ())` or `help?> Mumps()`. You can also inspect all the loaded docstrings with `MUMPS.__METADATA__`.

**Comment by MichaelHatherly** [comment]
Are both of those methods ([106](https://github.com/dpo/MUMPS.jl/blob/4511a4f63fa7f6ed41311f19077f71bbb97d796f/src/mumps.jl#L106) and [137](https://github.com/dpo/MUMPS.jl/blob/4511a4f63fa7f6ed41311f19077f71bbb97d796f/src/mumps.jl#L137)) callable?

If you have a no argument method and another with one optional argument (which produces two methods, one with no argument and another with a single argument) then the [`setdiff`](https://github.com/MichaelHatherly/Docile.jl/blob/b01e4eb959cb9dc0b609801394883926058e7a23/src/macros.jl#L122) used to find multiple method definitions might be getting confused.

What happens if you try to swap the order of the methods, ie. have the documented one appearing first?

**Comment by dpo** [comment]
The first returns an error, (`help?> Mumps()` returns nothing).
````
julia> query(Mumps, ())
ERROR: `_query!` has no method matching _query!(::Response, ::Set{Module}, ::Array{Symbol,1}, ::Type{Mumps}, ::())
 in query at /Users/dpo/.julia/v0.3/Lexicon/src/query.jl:143
````
I tried `@query`, which didn't reveal any more.

In [this other project](https://dpo.github.io/linop.jl/linop.html), the type and constructor are documented properly, but there's only one constructor (still its optional arguments disappeared). You might have an easier time examining that project, as it doesn't have external dependencies.

**Comment by MichaelHatherly** [comment]
From what I can tell the missing constructor issue is resolved using the new plain strings recently merged. There's likely to also be a problem in Lexicon's html rendering that's skipping certain documented objects anyway. I'll look into problems with `query`/`@query` further, though they may have been a symptom of the missing constructors already discussed. Thanks for your patience in dealing with these problems.

**Comment by dpo** [comment]
I see what you're saying about one constructor possibly shadowing the other. Calling `Mumps(sym)` is ambiguous. `methods(Mumps)` sees both though. I'm the one who's thankful for your carefully looking through this. I think the Docile-Lexicon-Markdown combo is a winning team!

**Comment by MichaelHatherly** [comment]
Yeah, the current execution order in `@doc` to deal with vararg method definitions producing multiple `Method` objects is at fault. Since individual `@doc` calls can't really talk to subsequent ones, the order of definition and documentation do appear to matter in this case.

**Comment by dpo** [comment]
You're right. Swapping them changes things. Now the convenience constructor appears in the documentation, but they don't both appear. Perhaps I have to rework their calling sequence.

**Comment by peter1000** [comment]
Reworking on the Lexicon side I thought that if we go with the signature as defined in the source code: we can skip the additional generated methods all together for all methods with set defaults: example:

```
"function `myrehash` with paramter types."
function myrehash{K,V}(h::Dict{K,V}, k::ByteString, newsz=length(h.keys), 
                       x::Dict{K,V}=Dict([(:con, 10)]); rm::Bool=false, 
                       prefix_ext::Dict{K,V}=Dict([(:remote, false)]))
end

```

currently generates: 3 entries

--- 

myrehash{K, V}(h::Dict{K, V}, k::Union(ASCIIString, UTF8String))

function `myrehash` with paramter types.

*source:*
[testing/src/testing.jl:35](https://github.com/peter1000/testing.jl/tree/46aadd060ee4c5778251730485262f34b0381b2c/src/testing.jl#L35)

---

myrehash{K, V}(h::Dict{K, V}, k::Union(ASCIIString, UTF8String), newsz) 

function `myrehash` with paramter types.

*source:*
[testing/src/testing.jl:35](https://github.com/peter1000/testing.jl/tree/46aadd060ee4c5778251730485262f34b0381b2c/src/testing.jl#L35)

---

myrehash{K, V}(h::Dict{K, V}, k::Union(ASCIIString, UTF8String), newsz, x::Dict{K, V}) 

function `myrehash` with paramter types.

*source:*
[testing/src/testing.jl:35](https://github.com/peter1000/testing.jl/tree/46aadd060ee4c5778251730485262f34b0381b2c/src/testing.jl#L35)

**Comment by peter1000** [comment]
##### In my view it should produce

---

MAIN:
   


function myrehash{K,V}(h::Dict{K,V}, k::ByteString, newsz=length(h.keys), x::Dict{K,V}=Dict([(:con, 10)]); rm::Bool=false, prefix_ext::Dict{K,V}=Dict([(:remote, false)]))

function `myrehash` with paramter types.

*source:*
[testing/src/testing.jl:35](https://github.com/peter1000/testing.jl/tree/46aadd060ee4c5778251730485262f34b0381b2c/src/testing.jl#L35)

---

MAYBE OPTIONAL 1

function myrehash{K,V}(h::Dict{K,V}, k::ByteString, newsz=length(h.keys), x::Dict{K,V}=Dict([(:con, 10)]))

function `myrehash` with paramter types.

*source:*
[testing/src/testing.jl:35](https://github.com/peter1000/testing.jl/tree/46aadd060ee4c5778251730485262f34b0381b2c/src/testing.jl#L35)

*kwargs:*

* rm=false
* prefix_ext=Dict([(:remote, false)])

---

MAYBE OPTIONAL 2
    
function myrehash(h, k)

function `myrehash` with paramter types.

*source:*
[testing/src/testing.jl:35](https://github.com/peter1000/testing.jl/tree/46aadd060ee4c5778251730485262f34b0381b2c/src/testing.jl#L35)

*default args*

* newsz=length(h.keys)
* x=Dict([(:con, 10)])

*kwargs:*

* rm=false
* prefix_ext=Dict([(:remote, false)])

---

MAYBE OPTIONAL 3

function myrehash(h, k, newsz=length(h.keys), x=Dict([(:con, 10)]))

*Types* 

function: myrehash{K,V}
parameters: 
* h::Dict{K,V}
* k::ByteString
* x::Dict{K,V}

function `myrehash` with paramter types.

*source:*
[testing/src/testing.jl:35](https://github.com/peter1000/testing.jl/tree/46aadd060ee4c5778251730485262f34b0381b2c/src/testing.jl#L35)

---

Or some similar combinations user definable

**Comment by peter1000** [comment]
@MichaelHatherly

Would appriciate your feeling about that above.

Anyway I came across a situation where I think it would not work

```
function convert{P<:Ptr,T<:Ptr}(::Union(Type{Ptr{P}},Type{Ref{P}}),a::Array{T})
end
```

if I reove the Parameter I end up with

```
function convert(,a)
end
```

```
ERROR: syntax: unexpected ,
```

Any Ideas

**Comment by MichaelHatherly** [comment]
> In my view it should produce only 1 entry

Yes, definitely.

For displaying the actual resulting signature the simplest way might be to just stack all available signatures. For `f(x, y = 2, z = 3) = ...` have:

```
f(x)
f(x, y)
f(x, y, z)

    docs...
```

In general Julian signatures tend to get quite complex sometimes and finding a general way to display the most relevant information to the user would be great.

**Comment by peter1000** [comment]
closed in favour of: https://github.com/MichaelHatherly/Lexicon.jl/issues/118
