### ISSUE TITLE
Filtering and sorting entries

### ISSUE THREAD

**Issue by tshort** [MichaelHatherly/Docile.jl#58]
It'd be great to have easier ways to sort and filter entries. I kludged up a version of `filter` that does the filtering part and a version of Lexicon's `save` that does the sorting part. Here are the results using [Mkdocs](http://mkdocs.org):

https://tshort.github.io/Sims.jl/

I've got code [here](https://github.com/tshort/Sims.jl/blob/mkdocs/docs/build.jl) that does some filtering and sorting. I filter based on groups of files. Types might also be a good thing to filter on. Sorting options I have were by name, source location, doctags, and category. 

I'm not sure what the best API for filtering and sorting should be. An iterator might work. That could combine filtering and sorting. Before I started on anything for a pull request, I wanted to get your feedback (and @one-more-minute's) to make sure this is the right place for it and if you have suggestions on an API. Whatever we do, it'd be nice to get that functionality in Base, too. It shouldn't take much code.

When putting this documentation together, the following work well:

* Filtering out by a file or set of files is a great way to group entries. 

* Sorting by location in a file is also useful for a lot of code, given that it's natural to group common types and methods. 

* When location sorting is used with what I call DocTags (dummy types used to place comments in appropriate places), it's easy to add headings or short comments among the entries. I'll file another issue on `DocTag`s (here or Base?).

* `@doc*` is more useful than `@doc`. I think `@doc*` should be the default, but I'll file that as another issue here or in Base.

**Comment by MichaelHatherly** [comment]
Yes, some kind of generic filter/sort api would be great. Your work looks like it's heading in the right direction. I think trying things out here and ironing out the rough spots is probably the best way to go, that's what I think anyway.

Not sure I follow the `DocTags` idea fully. Is there an example of it's use in the Sims.jl code base I can have a look at?

I currently prefer the behaviour of `@doc/@doc*` as it is now, but a separate issue to discuss that would be great. With the bare string syntax on Docile's master branch this might become a none issue, though I've yet to heavily experiment with the new syntax apart from in tests.

**Comment by tshort** [comment]
Here is a start at some code and API for discussions:

```julia

module X

using Docile, Docile.Interface, Sims


function Base.filter(m::Module; args...)
    filter(documentation(m); args...)
end

function Base.filter(docs::Metadata; categories = Symbol[], files = String[])
    entries = copy(docs.entries)
    if length(files) > 0
        filter!((k,v) -> any(x -> contains(v.data[:source][2], x), files),
                entries)
    end
    if length(categories) > 0
        filter!((k,v) -> any(x -> contains(category(v), x), categories),
                entries)
    end
    Metadata(docs.modname, entries, docs.root, docs.files, docs.data, docs.loaded)
end

writeobj(any)       = string(any)
writeobj(m::Method) = first(split(string(m), " at "))

type EachEntry
    parent::Documentation
    kidx
end
function EachEntry(docs::Documentation; order::Vector{Symbol} = [:category, :name, :source])
    ks = collect(keys(docs.entries))
    vs = collect(values(docs.entries))
    name = [replace(writeobj(k), ",", ", ") for k in keys(docs.entries)]
    source = [v.data[:source] for v in values(docs.entries)]
    category_ = [category(v) for v in values(docs.entries)]
    # doctag = [isa(k, Type) && k <: DocTag for k in keys(docs.entries)]
    d = [:name => name,    # various vectors for sorting
         # :doctag => !doctag,
         :source => [(a[2], a[1]) for a in source],
         :category => category_]
    idx = sortperm(collect(zip([d[o] for o in order]...)))
    EachEntry(docs, ks[idx])
end 

Base.length(x::EachEntry) = length(x.kidx)
Base.start(x::EachEntry) = 1
Base.done(x::EachEntry, state) = state == length(x.kidx)
Base.next(x::EachEntry, state) = ((x.kidx[state], x.parent.entries[x.kidx[state]]), state + 1)

d = documentation(Docile)

ee = EachEntry(d)

set1 = collect(EachEntry(d))

set2 = collect(EachEntry(d, order = [:source]))

set3 = collect(EachEntry(d, order = [:name]))

set4 = collect(EachEntry(d, order = [:category]))

# grab the filenames
cs1 = [v.data[:source][2] for (k,v) in EachEntry(d, order = [:name])]
    
# grab the filenames for a subset on files:
cs2 = [v.data[:source][2] for (k,v) in EachEntry(filter(d, files = ["types.jl"]), order = [:name])]
       
# grab the names for a subset on files:
cs3 = [writeobj(k) for (k,v) in EachEntry(filter(d, files = ["types.jl"]), order = [:name])]
       
end
```

**Comment by MichaelHatherly** [comment]
Great start, feel free to open this as a WIP in Lexicon if you've got the time.

Might be nice to be able take multiple modules (such as with `Docile` and `Docile.Interface`) and merge them together into a single output. I've found it quite annoying to have to generate docs for each module separately. Not sure how that all would work though.

**Comment by MichaelHatherly** [comment]
Sorting by exported/unexported could be worth including as well.

**Comment by tshort** [comment]
Any pointers on how to determine exported/unexported?

**Comment by MichaelHatherly** [comment]
`names(Docile)` gives a list of symbols exported and `names(Docile, true)` gives the unexported ones as well.

Though might be worth just capturing that info in each `Entry`'s `data` field instead, such as `:exported => true/false`, during docstring parsing. I'll have a look at that tomorrow.

**Comment by MichaelHatherly** [comment]
Closing since PR is now opened at https://github.com/MichaelHatherly/Lexicon.jl/issues/26.
