### ISSUE TITLE
@doc_mstr not defined error

### ISSUE THREAD

**Issue by jiahao** [MichaelHatherly/Docile.jl#64]
The latest master of `IterativeSolvers` now includes docstrings using the `@doc doc"" ->` syntax.

While the help works fine on julia 0.4-dev, the package no longer loads on julia 0.3.6-pre with Docile installed:

```jl
julia> using IterativeSolvers
ERROR: @doc_mstr not defined
 in include at ./boot.jl:245
 in include_from_node1 at ./loading.jl:128
 in include at ./boot.jl:245
 in include_from_node1 at ./loading.jl:128
 in reload_path at loading.jl:152
 in _require at loading.jl:67
 in require at loading.jl:51
while loading /Users/jiahao/.julia/v0.4/IterativeSolvers/src/factorization.jl, in expression starting on line 21
while loading /Users/jiahao/.julia/v0.4/IterativeSolvers/src/IterativeSolvers.jl, in expression starting on line 10
```

**Comment by MichaelHatherly** [comment]
Thanks for reporting this. Docile's syntax for when docstrings contain `$` is `@md_mstr`. I'll switch over to `@doc_mstr` in the next release. In the meantime you can change the line

```julia
VERSION < v"0.4-" && using Docile
```

to

```julia
if VERSION < v"0.4-"
    using Docile
    macro doc_mstr(text)
        Base.triplequoted(text)
    end
    macro doc_str(text)
        text
    end
end
```

to make this work in 0.3 with Docile.

**Comment by jiahao** [comment]
Thanks. This is quite the gotcha for 0.3.x backwards compatibility...

**Comment by MichaelHatherly** [comment]
Fixed by e57c6d81ffe7154fadbb1c2c122ea92e9025e246.

The purpose of the `@md_*` was to be able to specify the docstring format and avoid string interpolation all at once. @one-more-minute, was there a particular reason for going with `@doc_*` macros?

**Comment by one-more-minute** [comment]
Currently `doc""` and `md""` are equivalent. The idea in future is that you want to handle things like relative paths (links, images) quite differently in inline docs, so `doc""` will handle that in future.

**Comment by MichaelHatherly** [comment]
Cool, thanks for explaining. My current fix should be fine then.
