### ISSUE TITLE
Tag new release?

### ISSUE THREAD

**Issue by jiahao** [MichaelHatherly/Docile.jl#65]
The last release was a little while ago and I was trying to adapt @tshort's `build.jl` script but it apparently requires `master` to work properly.

**Comment by MichaelHatherly** [comment]
I'm was just waiting on https://github.com/MichaelHatherly/Lexicon.jl/pull/26 before tagging both Docile and Lexicon since there's a few cross-package dependencies currently. @tshort, if you're not able to work on that at the moment that's totally fine and I'll look into finalizing things without it for the moment.

**Comment by jiahao** [comment]
Thanks.

I've been playing around with mkdocs and really like it. I'm currently trying to figure out how to extract all the docstrings into a suitable format to be built with mkdocs.

**Comment by MichaelHatherly** [comment]
Yeah, mkdocs is really nice. Tom's build script is probably the best example available currently.

I'll probably write some quick build scripts based on that one for Docile and Lexicon today if I get a chance and then tag the next versions.

**Comment by jiahao** [comment]
I'm currently struggling with how to get `Docile.Interface.documentation` to recognize that a module is documented. Is it insufficient to have `@doc` strings for at least one object in the module?

**Comment by MichaelHatherly** [comment]
That should be sufficient. Does `Docile.Interface.documented()` contain the module you're trying to document?

**Comment by MichaelHatherly** [comment]
Closed by https://github.com/JuliaLang/METADATA.jl/pull/2014.
