### ISSUE TITLE
allow documentation to be skipped

### ISSUE THREAD

**Issue by peter1000** [MichaelHatherly/Docile.jl#72]
What I missed when looking at Lexicon was that some function/methods (internal used) where not documented which made it harder for someone outside to know what is going on.

What I would like to see is a possiblity to document all but allow some to be skipped in the output.  Maybe use for skipping a ! straight after the opening quotes.

This would allow proper documentation and if one wants to include them later: just remove the **!**.

e.g. 

```
"""! 
This is a documented function/method but skipped by Lexicon/Docile at the moment
"""
function a(b)
end
```

maybe something similar exist already in another way?

**Comment by MichaelHatherly** [comment]
Does the "exported" / "internal" distinction suffice for this? There's also an `include_internal` keyword for `save` to drop all non-exported docstrings and only display the "exported" section.

**Comment by peter1000** [comment]
> Does the "exported" / "internal" distinction suffice for this?

I'm not sure if that would be sufficent.

Imageing Lexicon would have every  function / method ect.. documented but only want to have the docs as they are....

Of course a work around is to use comment strings ... but in case one later decides to inlcude such into the documentation it needs to be redone.

Anyway .. just a thought...

**Comment by MichaelHatherly** [comment]
So would skipped docstrings still be read by Docile and appear in the REPL help but just not in the Lexicon-generated output? If you'd like them to not even be read by Docile then you might be able to get something like that now, kindof, by defining a method on `!`:

```julia
module Sandbox

using Docile
@document

(!)(str::String) = nothing

!""" 
This is a documented function/method but skipped by Lexicon/Docile at the moment
"""
function a(b)
end

end
```

we could probably get some standardised syntax here I think. I'd prefer not to have to dig into the actual string to find any `!` characters if possible.

**Comment by peter1000** [comment]
> If you'd like them to not even be read by Docile

Yes I had in mind that: just be able to document them with proper docstrings instead of comments but not to be read at all: call it a better comment string.

> we could probably get some standardised syntax here I think.

If you could do a `official`  standardised syntax here would be great.

**Comment by MichaelHatherly** [comment]
I'll give the syntax some thought.

**Comment by peter1000** [comment]
`(!)(str::String) = nothing`  would this effect any other string operations in the code too?

**Comment by MichaelHatherly** [comment]
Best way to test would be to add that definition to a module you're documenting and see what happens :) I've not come across that definition so far, so it's probably safe. I'd personally just go with a multiline comment such as

```julia
#=
"""
My unfinished docs ...
"""
=#
f(x) = x
```

Might make things clearer to readers that it's commented out without needing to know some Docile-specific syntax.

**Comment by peter1000** [comment]
Tha is a good suggestion.
