### ISSUE TITLE
Questions about custom documentation objects

### ISSUE THREAD

**Issue by shashi** [MichaelHatherly/Docile.jl#73]
I am generating a bunch of methods using a macro and also generating some objects (to start off with, just whatever `meta` returns) for the documentation. The generated code effectively looks like this:
```julia
immutable Width <: Tile
    w::Length
    tile::Tile
end

@doc* meta("set the width", typ=:(Width <: Tile), name=:width, args={{:type=>:Length,:curried=>false,:coerced=>true,:kwarg=>false,:name=>:w},{:type=>:Tile,:curried=>true,:coerced=>true,:kwarg=>false,:name=>:tile}}]) ->

width(w, tile) = Width(w, tile)
width(w) = tile -> Width(w)
```

Now after including Lexicon if I look up the documentation, the following happens
```julia
help?> width
width (generic function with 4 methods)


[function]

Canvas.width
Error showing value of type QueryResults:
ERROR: BoundsError()
 in plain at /home/shashi/.julia/v0.3/Markdown/src/render/plain.jl:8
 in writemime at /home/shashi/.julia/v0.3/Markdown/src/render/plain.jl:66
 in writemime at /home/shashi/.julia/v0.3/Lexicon/src/render/plain.jl:4
 in writemime at /home/shashi/.julia/v0.3/Lexicon/src/render/plain.jl:80
 in writemime at /home/shashi/.julia/v0.3/Lexicon/src/render/plain.jl:49
 in writemime at /home/shashi/.julia/v0.3/Lexicon/src/render/plain.jl:23
 in display at REPL.jl:117
 in display at REPL.jl:120
 in display at multimedia.jl:149
 in print_response at REPL.jl:139
 in print_response at REPL.jl:124
 in anonymous at REPL.jl:586
 in run_interface at ./LineEdit.jl:1379
 in run_frontend at ./REPL.jl:818
 in run_repl at ./REPL.jl:169
 in _start at ./client.jl:400
```

cc @one-more-minute

I am pretty sure I'm doing something wrong here though. I was expecting the help look up to result in `set the width` being printed.

My questions are:
1. What is the correct way to attach arbitrary objects as documentation?
2. What is the correct way to define how it gets rendered in the terminal or in the web browser? `writemime` methods?
3. How do I get an ordered list of documentation objects I can use to generate my own documentation? (sort of like Lexicon)

I'll continue to look for answers, but thought it could be faster if I asked first.

Thanks!

**Comment by MichaelHatherly** [comment]
Odd, I'm not getting that error with the following (should be equivalent to yours):

```julia
module Sandbox

using Docile

abstract Tile
abstract Length

immutable Width <: Tile
    w::Length
    tile::Tile
end

@doc+ meta("set the width",
           typ  = :(Width <: Tile),
           name = :width,
           args = {
               {:type    => :Length,
                :curried => false,
                :coerced => true,
                :kwarg   => false,
                :name    => :w},
               {:type    => :Tile,
                :curried => true,
                :coerced => true,
                :kwarg   => false,
                :name    => :tile
                }}) ->

width(w, tile) = Width(w, tile)
width(w) = tile -> Width(w)

end
```

```
help?> Sandbox.width
INFO: Loading help data...
width (generic function with 2 methods)


[function]

Sandbox.width

  set the width

 Details:

	source: (27,"/home/mike/sand.jl")
	typ: Width <: Tile
	name: width
	args:
		{:type=>:Length,:curried=>false,:coerced=>true,:kwarg=>false,:name=>:w}
		{:type=>:Tile,:curried=>true,:coerced=>true,:kwarg=>false,:name=>:tile}
```

You're using `0.3` so there should be any trouble with interference from `Base.Docs`, what's the exact `versioninfo()` output?

**Comment by MichaelHatherly** [comment]
Output of `args` should be nicer... I'll look into printing those out better.

**Comment by shashi** [comment]
Version info
```
Julia Version 0.3.5
Commit a05f87b* (2015-01-08 22:33 UTC)
Platform Info:
  System: Linux (x86_64-linux-gnu)
  CPU: Intel(R) Core(TM) i5-3210M CPU @ 2.50GHz
  WORD_SIZE: 64
  BLAS: libblas.so.3
  LAPACK: liblapack.so.3
  LIBM: libopenlibm
  LLVM: libLLVM-3.3
```

What I would like to do is, take these objects and then output some custom "HTML".

For the actual macro generating this code, see: https://github.com/shashi/Canvas.jl/blob/documentation/src/basics/macros.jl#L334

**Comment by MichaelHatherly** [comment]
> 1. What is the correct way to attach arbitrary objects as documentation?

Currently Docile just accepts strings or `meta`. What kind of objects do you have in mind?

> 2. What is the correct way to define how it gets rendered in the terminal or in the web browser? writemime methods?

All the `writemime` method are in Lexicon. They're probably going to go through some revisions relatively soon though.

> 3. How do I get an ordered list of documentation objects I can use to generate my own documentation? (sort of like Lexicon)

The `Docile.Interface` module contains several methods for extracting documentation.

**Comment by shashi** [comment]
Okay, if I run the example code (Sandbox module) you posted, I don't get the error. I suppose there is a problem in my code somewhere.

**Comment by shashi** [comment]
> What kind of objects do you have in mind?

UI objects from the Canvas library basically. Complicated layouts, in lined Gadfly plots etc. There is a server which can render these UI objects in the browser, so I would like to use that.

> All the `writemime` method are in Lexicon. 
So I suppose if there is support for attaching arbitrary objects as documentation, then I could go to town with my own `writemime`s?

> The Docile.Interface module contains several methods for extracting documentation.

Nice! That's helpful. Thanks!

**Comment by MichaelHatherly** [comment]
Possibly related to https://github.com/shashi/Canvas.jl/blob/a532a83f73eec8d1e7ca8a1c09bcdf7100912805/src/basics/macros.jl#L341. I've not ever tried using `@doc` like that. I'll poke at it with `macroexpand` a bit.

**Comment by shashi** [comment]
Yeah, it's a pretty fringe piece of code. `ms` is a vector of method definitions here.

**Comment by MichaelHatherly** [comment]
> UI objects from the Canvas library basically. Complicated layouts, in lined Gadfly plots etc. There is a server which can render these UI objects in the browser, so I would like to use that.

That sounds awesome! I'd definitely like to allow for that kind of thing.

**Comment by shashi** [comment]
Just the relevant part of the expansion looks like this:

```julia
begin 
    isdefined(:__METADATA__) || const __METADATA__ = Docile.Metadata(Docile.current_module(),"/home/shashi/.julia/v0.3/Canvas/src/basics/layout.jl",Docile.docstrings())
    begin 
        begin  # /home/shashi/.julia/v0.3/Canvas/src/basics/macros.jl, line 341:
            width(#396#prefix::String,#397#w,#398#tile) = Width(#396#prefix,#397#w,#398#tile)
        end
        Docile.setmeta!(current_module(),width,:function,(341,"/home/shashi/.julia/v0.3/Canvas/src/basics/macros.jl"),("",[:typ=>:(Width <: Tile),:name=>:width,:args=>{{:type=>:String,:curried=>false,:coerced=>true,:kwarg=>false,:default=>"",:name=>:prefix},{:type=>:Length,:curried=>false,:coerced=>true,:kwarg=>false,:name=>:w},{:type=>:Tile,:curried=>true,:coerced=>true,:kwarg=>false,:name=>:tile}}]))
        width
    end
end
```

**Comment by MichaelHatherly** [comment]
Manually adding that to a `Metadata` object at the repl works fine (it's definitely legal Docile input), but the `""` docstring appears to be causing Markdown some problems.

**Comment by shashi** [comment]
Oh, you're right! Replacing empty string with "undocumented" e.g. fixes this. Sorry about the misleading initial example :P

**Comment by MichaelHatherly** [comment]
No prob, glad to see what others are doing to docs.

Looks like it's just https://github.com/one-more-minute/Markdown.jl/blob/f1e0165ccd8513fee3f67b1943ec669d380b9d62/src/render/plain.jl#L8 that's the problem. @one-more-minute do you want PRs to the package or to base (if it's actually an issue in base)?

**Comment by shashi** [comment]
Closed. My questions got answered I guess! :)
