### ISSUE TITLE
Preprocessing custom docstring formats.

### ISSUE THREAD

**Issue by dcjones** [MichaelHatherly/Docile.jl#77]
I want to enforce a particular documentation standard in some packages. So I had the idea that I'd use Docile with a custom docstring format, and that format would validate the docstring on construction. What I wish I could do is define a constructor for `Docs` in my package like:
```julia
function Docile.Docs{:myformat}(data::AbstractString)
    # Check that data is correctly formatted according to "myformat" then
    # construct a Docs{:myformat} object
end
```
but dispatch doesn't work that way. So I think doing this would require some changes to Docile.

What occurred to me to do is define a type (very similar to how MIME is defined in Base)
```julia
immutable Format{format} end
```

Then change `Docs` to be like
```julia
type Docs{format <: Format}
    ....
end
```

With a constructor like
```julia
function Docs(format::Format, data::AbstractString)
    Docs{format}(data)
end
```

And now I can define `Docs{::Format{:myformat}, data::AbstractString)` in my package and get the behavior I desire.

I'm happy to make a PR for this, but wanted to get some input on the least offensive way to add this, or wether you think it's even worth adding.

**Comment by MichaelHatherly** [comment]
I think what you want *might* already be possible.

```julia
module T

using Docile
@docstrings(format = :my_format) # Change the default from `:md` to custom one.

@doc " ... " ->
f(x) = x

# Verification and display methods needed.

import Markdown

# Overload the parsing of `:my_format` format `Docs` objects.
# Usually just takes a raw string and creates a markdown ast object.
function Docile.Interface.parsedocs(ds::Docile.Docs{:my_format})
    raw = Docile.Interface.data(ds) # The unprocessed string captured by Docile.
    
    # verification ...
    
    raw = "# Default header\n\n" * raw # Perhaps add a header to everything.
    Markdown.parse(raw)                # Convert to the final format. Return result.
end

# This overload is currently needed since Lexicon doesn't defined a generic fallback yet.
function Base.writemime(io::IO, mime::MIME"text/plain", ds::Docile.Docs{:my_format})
    writemime(io, mime, Docile.Interface.parsed(ds))
end

end
```

```
julia> include("scratch/test.jl")

julia> using Lexicon

help?> T.f
INFO: Loading help data...
f (generic function with 1 method)


[method]

T.f(x)

                                     Default header
                                    -––––––––––––––-

  ... 

 Details:

	source: (6,"/home/mike/scratch/test.jl")
```

Is this the kind of thing you were looking to do?

The need for the extra `writemime` definition could definitely be done away with. All you should need to do is overload the `Docile.Interface.parsedocs` method and use a custom format.

Generating static output will need a few changes to Lexicon perhaps.

**Comment by MichaelHatherly** [comment]
Also works just the same with plain docstrings by changing:

```julia
@docstrings(format = :my_format) # Change the default from `:md` to custom one.

@doc " ... " ->
f(x) = x
```
to
```julia
@document(format = :my_format) # Change the default from `:md` to custom one.

" ... "
f(x) = x
```

**Comment by MichaelHatherly** [comment]
> `immutable Format{format} end`

Having the format specified as a custom type rather than just `Symbol` would probably have been a better choice since modules could then still be able to defined their `Format` the same as another module's without clashing, I believe. Might be worth changing that.

**Comment by MichaelHatherly** [comment]
Another thing... the docstring parsing is left until they're actually queried by Lexicon. Only then is `parsedocs` called on a docstring. So if you'd like to verify all of them you'd need to use `Docile.Interface.metadata(MyModule)` to parse and verify them in a batch. This could be done in the module itself, but will slow the loading time down a little. Running it as part of a test suite would probably be best.

**Comment by dcjones** [comment]
Thanks, this is very useful. It would actually be fine, and maybe preferable, if it validated docstrings on demand rather than when they're loaded. As long as pull-requests with bad docstrings are automatically shamed. :wink:

It seems like `parsedocs` isn't normally called until the documentation is being printed for the first time. It works if I add something like this to tests though.
```julia
using Docile.Interface
for (obj, entry) in entries(metadata(MyModule))
	parsed(docs(entry))
end
```

**Comment by MichaelHatherly** [comment]
> It seems like `parsedocs` isn't normally called until the documentation is being printed for the first time. It works if I add something like this to tests though.

Yes, that's the usual way I'd go about doing that. We could potentially add a method for that as `Interface.verifydocs(::Module)` or some more apt name.
