### ISSUE TITLE
 both Docile and Base export "@doc"; uses of it in module PackageName must be qualified

### ISSUE THREAD

**Issue by yfractal** [MichaelHatherly/Docile.jl#79]
Julia Version 0.4.0-dev+4504 (2015-04-26 02:17 UTC) (the newest version of Julia ...)

```

julia> module PackageName

       using Docile
       @doc """
       ...
       """
       end
Warning: both Docile and Base export "@doc"; uses of it in module PackageName must be qualified
ERROR: UndefVarError: @doc not defined

```

we can use ` Docile.@doc ` to qualify the `@doc`. But do we have other way to this?

**Comment by MichaelHatherly** [comment]
Hi @yfractal,

If you're using `@doc` with Julia 0.4 you should be using the one provided by `Base`. To support 0.3/0.4 within a package you need to conditionally import Docile like so:

```julia
module T

VERSION < v"0.4-" && using Docile

@doc " ... " ->
f(x) = x

end
```

This is outlined in the section "Backwards compatibility with julia 0.4's `@doc`" of http://docilejl.readthedocs.org/en/stable/manual/. If the explanation found there isn't clear please do let me know, or send a PR to fix the wording if you'd like too.

**Comment by yfractal** [comment]
@MichaelHatherly 
Thanks for you reply :) !

The Julia changed too fast ....

**Comment by dpo** [comment]
I feel like this is a very silly question, but what's going on here?
````
$ cat ~/.julia/v0.3/Testmodule/src/Testmodule.jl
module Testmodule

if VERSION < v"0.4.0-dev"
  using Docile
  @docstrings
end

end
````
Then:
````
julia> VERSION
v"0.3.6"

julia> using Testmodule
ERROR: @docstrings not defined
 in include at /usr/local/Cellar/julia/0.3.6_1/lib/julia/sys.dylib
 in include_from_node1 at /usr/local/Cellar/julia/0.3.6_1/lib/julia/sys.dylib
 in reload_path at loading.jl:152
 in _require at loading.jl:67
 in require at loading.jl:51
while loading /Users/dpo/.julia/v0.3/Testmodule/src/Testmodule.jl, in expression starting on line 3
````

**Comment by dpo** [comment]
Also happens on Travis: https://travis-ci.org/dpo/LinearOperators.jl/jobs/60616239#L78

**Comment by yfractal** [comment]
@dpo 

In my understanding,
I think these relate how macro works.

Please see the code below

```

foo() = println("foo is called")

macro ma()
    println("ma macro is called")
end

# please see of the executed order, the @ma is called first then foo

if true
    foo()
    @ma
end


```

when Julia will "translate" macro to normal sentence first.

So Julia reads

```

if VERSION < v"0.4.0-dev"
  using Docile
  @docstrings
end

```
Julia will first try to get ` @docstrings` to another sentence, but it has not execute `using  Docile`,
so Julia doesn't know `@docstrings` meaning. ..

Hope I explain it clearly and correctly ...

**Comment by dpo** [comment]
[The documentation](http://docilejl.readthedocs.org/en/stable/manual/#overview) recommends to use
````
using Docile
@docstrings
````
and I'm quite sure it used to work until very recently. @MichaelHatherly.

**Comment by MichaelHatherly** [comment]
Yes, @yfractal I think that's probably what's happening.

@dpo, if you don't need to provide a `format =` or `manual =` option to `@docstrings` then you can skip writing `@docstrings` entirely since `@doc` now does the setup if necessary.

If you do need to add an option, then `eval` can work:

```julia
if VERSION < v"0.4.0-dev"
    using Docile
    eval(:(@doctrings(manual = ["../README.md"])))
end
```

**Comment by dpo** [comment]
That's really silly and I would expect it will bite many times.
````
$ cat foo.jl
foo() = println("Function foo")

macro mac()
  println("Macro mac")
end

if true
  foo()
end
if true
  @mac
end
````
produces
````
$ julia foo.jl
Function foo
Macro mac
````
yet if the two `if`s are merged into one, the output is reversed.

**Comment by argriffing** [comment]
This just bit me when I tried installing @dpo's LinearOperators.  How would I fix this, pretending that I don't know anything about Julia?

**Comment by dpo** [comment]
@argriffing It's been fixed already in the `develop` branch.

**Comment by MichaelHatherly** [comment]
@argriffing you could done one of the following:

Explicitly import ``@doc`` from Docile to avoid the ``both Docile and Base export "@doc"`` warning/error:

```jl
import Docile: @doc
```

Conditionally import Docile in Julia 0.3 only:

```jl
VERSION < v"0.4-dev" && using Docile
```

Use bare docstrings instead of directly using ``@doc``:

```jl
# instead of
@doc "..." ->
foo(x) = ...

# use
"..."
foo(x) = ...
```

I'd strongly recommend going with option 3, bare docstrings, since that's what we've been working on adding to Julia 0.4 over the last few months. Docile is able to extract bare docstrings as well in Julia 0.3 so this approach should be compatible with stable and dev versions.

What you can do to make the transition between 0.3 and 0.4 as seamless as possible is to do something like:

```jl
module Foo

# Automatically hook into the REPL's help system and extracts bare docstrings on demand.
VERSION < v"0.4-dev" && import Lexicon

" docs ..."
foobar(x) = ...

end
```

**Comment by MichaelHatherly** [comment]
Ah, so it's been fixed already :) hope what I wrote is helpful to someone anyway.

**Comment by dpo** [comment]
@MichaelHatherly Thanks! It is very helpful indeed and I probably should convert to bare docstrings. An advantage of `Docile`'s `@doc` is that it lets me specify what a function returns. Will bare docstrings let me do that as well?

**Comment by MichaelHatherly** [comment]
> Will bare docstrings let me do that as well?

Not at the moment. The consensus reached, I think, was that any metadata should be specified in a more human-readable rather than machine-readable way. We can always teach the docsystem how to extract metadata once an agreed upon format is found.
