### ISSUE TITLE
Argument types in documentation.

### ISSUE THREAD

**Issue by peter1000** [MichaelHatherly/Docile.jl#84]
I'm trying to understand Docile a little bit and are going through some of the code.

I have a question regarding the `argtypes` in the output of the documentation.

e.g.: in documentation

![screenshot from 2015-04-28 22-01-50](https://cloud.githubusercontent.com/assets/6168860/7383238/69e210e6-edf2-11e4-9860-0173d3660e82.png)

source: https://github.com/MichaelHatherly/Docile.jl/blob/master/src/interface.jl#L76

![screenshot from 2015-04-28 22-04-09](https://cloud.githubusercontent.com/assets/6168860/7383258/a687bae6-edf2-11e4-9e7d-ccab82c913a3.png)

Do you thing it is required to have the `module` added.

Sometimes it gets quite long: Docile/src/types.jl:129

```
pushmeta!(doc::Metadata, object, entry::Entry)
```
becomes

```
pushmeta!(doc::Docile.Metadata, object, entry::Docile.Entry{category})
```

I just wonder if it should not appear in the documentation as the original source was written.

I know the extra added info has some value but just asking - if for instance this could be optional or as extra info like meta data source or so

I'm asking especially as we consider also to add the `kwargs` then this might get real long and might be not so easily readable?

This happens already with some of the `call` things.
```
call{format}(::Type{Docile.Docs{format}}, docs::Docile.Docs{format})
```
source points to: https://github.com/MichaelHatherly/Docile.jl/blob/master/src/types.jl#L24
```
Docs(docs::Docs) = docs
```

I find such hard on the eye eventhough there might be extra info.

**Comment by peter1000** [comment]
Basic idea behind it: if the code author did not not plan to fully specify the types - maybe it should also not be automatic in the generated documentation.

**Comment by MichaelHatherly** [comment]
Yes, it will get really long if we start adding `kwargs` there as well. I'd prefer something like a list or table of the keywords and their default values added in the metadata section of the output.

Regarding the module-qualified output, 0.4 changed the printing of objects to always display their full names. So we need to decide whether to match the output of julia itself, or clean up things where possible. That also goes for the `call` overloading, we'd need to special case `call` and rewrite the signature.

**Comment by peter1000** [comment]
Yes the call things looks ugly at best.

My personal feeling is it should be like in the source code: if a developer things the Types are important so might it be in the docu - if a coder things it is not important in the code neighter should it be a problem for the documentation

**Comment by MichaelHatherly** [comment]
So the beginnings of signature rewriting is already in https://github.com/MichaelHatherly/Lexicon.jl/blob/a145a3b6fcbb38869494355ed79111b2bcafa7e7/src/render.jl#L216-L223. We'd just need to decide on what to rewrite and what not to.

Perhaps the following rules:

Module-qualified objects should have the module removed **if** they're from the current module.

Rewriting `call` as

```
call{format}(::Type{Docile.Docs{format}}, docs::Docile.Docs{format})

 ->

Docs{format}(docs::Docs{format}))
```

Not sure how simple this will be though.

**Comment by peter1000** [comment]
Closed in favour of: https://github.com/MichaelHatherly/Lexicon.jl/issues/118
