### ISSUE TITLE
Line number to point to docstring start.

### ISSUE THREAD

**Issue by peter1000** [MichaelHatherly/Docile.jl#86]
Just a thought: maybe the source should point to the start line of the documentationstring.

This would avoid the ofline issue sometimes happens if there are empty lines between doctring and documented object.

And especially it would avoid the a bit annoying line offset for comments.

* Comments are supposed to:  *Add additional commentary to source code unrelated to any particular object.*
good we have the new reference links ;) 

  http://docilejl.readthedocs.org/en/latest/api/Docile/index.html?highlight=comment#macro___comment.1

But currently they are always associated with the next object especially the line number.

Anyway just a thought for later dicussion maybe worthy to not loose.

**Comment by MichaelHatherly** [comment]
We'd need to get the `LineNumberNode` above the docstring for this to work. I prefer the link pointing to the implementation though, since if you've read the docstring and then clicked on the link you'd probably not want to scroll back through the text again. (Just personal preference though, so if you'd like to see how it works out with the reference at the start then go for it. I could be persuaded.)

**Comment by peter1000** [comment]
I might do that after we have implemented the Lexicon things.
Strictly speaking the LineNumberNode above are the correct once: [see discussion](https://github.com/JuliaLang/julia/issues/10578#issuecomment-97652920) and the reply from **toivoh**

**Comment by MichaelHatherly** [comment]
> Strictly speaking the LineNumberNode above are the correct once: see discussion and the reply from **toivoh**

---

> where a line number annotation applies to the expression(s) that follows it. This is a very reasonable format, I think

For the purpose of locating the *definition* that is being documented rather than the top of the docstring this is the correct behaviour, so I'm not sure I understant your "corrent one" assertion. It's behaving exacting how I'd expected it to.

`@comment` could possibly change to point to above though.

**Comment by peter1000** [comment]
> I'm not sure I understant your "corrent one" assertion.

I meant from the reply of  ** toivoh** where I mentioned that the `last` obj never has an line number.  So the `LineNumberNode above` is the correct one in this sense. [comment](https://github.com/JuliaLang/julia/issues/10578#issuecomment-97652920)


```
begin  # /home/workerm/0__DATA__0/TEST_LEXICON/testing.jl, line 3:
    a = 1 # line 7:
    function tests() # /home/workerm/0__DATA__0/TEST_LEXICON/testing.jl, line 11:
        a = f
    end # line 17:
    const gg = 5
end
```
Correctly grouped is it:

```
# /home/workerm/0__DATA__0/TEST_LEXICON/testing.jl, line 3::  a = 1 
# line 7:  function tests() 
# /home/workerm/0__DATA__0/TEST_LEXICON/testing.jl, line 11: a = f
# line 17: const gg = 5
```

I meant that: of course I understand your point that you want to go to the source of the documented obj - but it is a other grouping with is especially seen in the Comments which have no second obj code like a function

Also the example above has no documentation strings.

**Comment by MichaelHatherly** [comment]
Ok, that makes more sense. Just wasn't reading that properly. Thanks.

Comments should indeed point to the top of the string. Normal docstrings source location is more debatable, but you're welcome to work on that if you'd like to and we can judge the result against what we currently have.

**Comment by peter1000** [comment]
I may but I think the general Lexicon stuff should first be done.

**Comment by MichaelHatherly** [comment]
Sure.

**Comment by peter1000** [comment]
just a related thought: because of the argumentation that one has already read the doc and now wants to go to the code source. (I agree)

but for example in python numby one gets always additionally first the docstring again because of the way python positions doc strings.

e.g. [numpy.pmt](http://docs.scipy.org/doc/numpy/reference/generated/numpy.pmt.html#numpy.pmt) clicking source (which is interestingly at the top of the documentation)

**Comment by MichaelHatherly** [comment]
> but for example in python numby one gets always additionally first the docstring again because of the way python positions doc strings.

Good point, a less surprising behaviour for users coming from other languages should be important.

> e.g. numpy.pmt clicking source (which is interestingly at the top of the documentation)

Source link at the top is quite nice.

**Comment by peter1000** [comment]
> Source link at the top is quite nice.

I thought so too. 

Personally I like to jump to the code source so I fully understand what you do - but when I used first julia and the line numbers where off - I found that a bit annoying. 

One solution might be quite nice: `[source] [code]`   but of course could just be a char `[*]` so not to waist space depending where it is placed.

The top is quite nice but julia has much longer signatures - so we have to see.

If you think this is worthy something like this choose on purpose a longer docstring

**@doc**(*args...*) [source](https://github.com/MichaelHatherly/Docile.jl/blob/master/src/macros.jl#L148) [code](https://github.com/MichaelHatherly/Docile.jl/blob/master/src/macros.jl#L246)

**@doc**(*args...*) [source](https://github.com/MichaelHatherly/Docile.jl/blob/master/src/macros.jl#L148) [*](https://github.com/MichaelHatherly/Docile.jl/blob/master/src/macros.jl#L246)

Than maybe Docile could provide both line numbers or a tuple: (sourceline, codeline)

for comments both would be the same

Just a though not sure if it would be worthy but maybe?

**Comment by MichaelHatherly** [comment]
> One solution might be quite nice: `[source] [code]` but of course could just be a char `[*]` so not to waist space depending where it is placed.

I'd think of "source" and "code" as synonyms most of the time. Perhaps "text" and "source"? "\*" and "\*\*" might be a bit cryptic.

> Than maybe Docile could provide both line numbers or a tuple: (sourceline, codeline)

That should be workable. I'll look into adding it to the experimental module and see how it goes.

**Comment by peter1000** [comment]
just the general idea -what we name it will not matter mach - I'm unsure if we can/ should put it on the definition line though as we have long once and already the `permalink`.

Anyway I tried to shorten them and the best I came up are this 2 new option:

---

This is my planned design for the display of the new methods definitions and if you are ok (or has some other ideas) I would like to implement it like that.

Based on other documentation (especially python and numpy) I would like to add 2 new options.

After some thoughts how to simplyfy some of the parametric julia things I hope to do it this way.

* **sig_curly**       if true keep all as in the orignial code: if false removes all curly content
* **sig_spaces**      if true add some extra space between items if false all spaces are stripped.


This will allow a clean unified output.

##### EXAMPLE

Note the inconsitance in use of spaces between items

```
function newdesign{P <: Ptr,T<:Ptr}(::Union(Type{Ptr{P}},Type{ Ref{ P } }), a::Array{T})
end
```

###### EXPECTED OUTPUT:

* sig_curly=true, sig_spaces=true:  the longest
    
  * newdesign{P <: Ptr, T <: Ptr}(::Union(Type{Ptr{P}}, Type{Ref{P}}), a::Array{T})

* sig_curly=false, sig_spaces=false:  the shortest

  * newdesign(::Union(Type,Type),a::Array)

sig_curly=false, sig_spaces=true

  *  newdesign(::Union(Type, Type), a::Array)

sig_curly=true, sig_spaces=false: all info but a a bit hard to read

  *  newdesign{P<:Ptr,T<:Ptr}(::Union(Type{Ptr{P}},Type{Ref{P}}),a::Array{T})

**Comment by MichaelHatherly** [comment]
I'm not sure about removing parametric type information in the `{...}`, I've found it quite useful when reading signatures.

How about expanding a signature over multiple lines when it exceeds a max width (we should be able to get console width in the REPL)?

**Comment by peter1000** [comment]
**parametric type information**

This is a bit hard as you said the info is quite useful - but in the case above we have not even any default args or kwargs.

maybe do it as an option to remove them from the header but add the full one a line below: maybe use some htmls code to make them a bit smaller than the rest of the text.

something like this:

```
function newdesign{P <: Ptr,T<:Ptr}(::Union(Type{Ptr{P}},Type{ Ref{ P } }), a::Array{T})
end
```

**sig_curly=false**

---

**newdesign**(::Union(Type, Type), a::Array) <a href="#method__meta.2">¶</a>

newdesign{P <: Ptr, T <: Ptr}(::Union(Type{Ptr{P}}, Type{Ref{P}}), a::Array{T})

Add additional metadata to a documented object.

meta takes arbitrary keyword arguments and stores them internally as a Dict{Symbol,Any}. The optional doc argument defaults to an empty string if not specified.

Examples:

The syntax previously used (in versions prior to 0.3.2) was

---

**Decision: space question**

   * optional to remove all or just fix have space between items?

**Comment by MichaelHatherly** [comment]
> optional to remove all or just fix have space between items?

I'd say have a single space after each `,` and a space before and after `<:` without options to change that.

> maybe do it as an option to remove them from the header but add the full one a line below

That could be alright, a bit repetitive though...

For splitting over lines we could have the following:

```
newdesign{
    P <: Ptr, T <: Ptr
}(
    ::Union(Type{Ptr{P}}, Type{Ref{P}}),
    a::Array{T}
)
```

when the `{}` is still too long

```
newdesign{
    P <: Ptr,
    T <: Ptr
}(
    ::Union(Type{Ptr{P}}, Type{Ref{P}}),
    a::Array{T}
)
```

If a single argument's parameter is *still* too long, give up :)

This is the kind of thing I'd do with signatures in code anyway.

**Comment by peter1000** [comment]
I don't think doing it multilines will work with the headers mkdocs produces though - will have to check that out.

:+1: Space question descided

I think I will work on the other thing and come back (might be a couple of days as my wife comes back and I won't be so much on the PC)

**Comment by MichaelHatherly** [comment]
> what we name it will not matter mach

FYI, went with `:textsource` and `:codesource` as the fields in 434f22edba8e55c6ae3423f38657161bf4c4aff1.

**Comment by peter1000** [comment]
Can I use that already with the `old` Docile from master too?

**Comment by MichaelHatherly** [comment]
> I don't think doing it multilines will work with the headers mkdocs produces though

Uggh! Forgot about that :(

**Comment by MichaelHatherly** [comment]
> Can I use that already with the old Docile from master too?

It's a bit of a breaking change currently. I'll have a think about how to make it less so. Perhaps for the moment just use the `:source` info for both "text" and "code" then we just need to change one later on.

**Comment by peter1000** [comment]
Nop: I think I will go straight with the new Docile - in that way I can give some feedback.

No point to backport everything.

I do not understand the new design but it seems it is radically different - so I would go with an break and improve the new so that everyone wants to change anyway - instead of trying to be completely backwards compatible.

Just leave the old Docile version in META for people who do not want to switch

**Comment by peter1000** [comment]
one more thing to consider: maybe for the new Docile require julia 4 from start on?

**Comment by MichaelHatherly** [comment]
> I think I will go straight with the new Docile - in that way I can give some feedback what is clear and what is confusing.

`Interface` hasn't been written just yet, I'll see if I can get something up tonight maybe.

> I do not understand the new design but it seems it is radically different

Basically:

- Capture module info by finding the file info of methods and macros defined in a module. [here](https://github.com/MichaelHatherly/Docile.jl/blob/434f22edba8e55c6ae3423f38657161bf4c4aff1/src/Experimental/Collector/search.jl#L28)
- Put submodules together into packages. [here](https://github.com/MichaelHatherly/Docile.jl/blob/434f22edba8e55c6ae3423f38657161bf4c4aff1/src/Experimental/Collector/types.jl#L60)
- Use the file info to extract docstrings as in the current version. Just without `loopdocs`. [here](https://github.com/MichaelHatherly/Docile.jl/blob/434f22edba8e55c6ae3423f38657161bf4c4aff1/src/Experimental/Runner/lookup.jl#L10)
- Store raw docstrings and metadata in two `ObjectIdDict`s rather than special `Entry` types. [here](https://github.com/MichaelHatherly/Docile.jl/blob/434f22edba8e55c6ae3423f38657161bf4c4aff1/src/Experimental/Cache/types.jl#L6)
- Have a third `ObjectIdDict` to store the "parsed" form of all raw docstrings.
- Each documented module has a set of three `ObjectIdDict`s.

There's not a huge amount different, mostly just streamlining and avoiding hooking into `include` as is currently done.

> Just leave the old Docile version in META for people who do not want to switch

It'll just be a minor version bump, everything that now works should continue to work (hopefully). For Lexion some changes will be needed, but I've done a few breaking changes between the two previously so that should be easy to handle.

> maybe for the new Docile require julia 4 from start on

It will all be 0.3/0.4 compatible I should think.

**Comment by peter1000** [comment]
great info thankt - I'm sure I will have a number of related questions

Anyway you solved this issue: FYI, went with :textsource and :codesource as the fields in 434f22e.

**Comment by peter1000** [comment]
**Put the screenshots here so you do not have to spend much time clicking around**

Just for info:

 looked a bit at Rust documentation: they seem to have given it also quite some good thoughts. Anyway see how they have put the source link plus something additional at the top: the  [-] collabses documentation.

---

https://doc.rust-lang.org/rand/rand/index.html#

![screenshot from 2015-05-04 08-16-23](https://cloud.githubusercontent.com/assets/6168860/7452594/06d1a60e-f236-11e4-86a0-ed78ffba1e74.png)

---
http://doc.rust-lang.org/nightly/std/ascii/fn.escape_default.html

the hyperlink of [source]  is quite nice: it specifies the start and end line of the code. **#353-373**


```
http://doc.rust-lang.org/nightly/src/std/ascii.rs.html#353-373
```
If one clicks it this lines are marked on github - does not need much extras on ourside except we need the end line of the code

![screenshot from 2015-05-04 08-24-11](https://cloud.githubusercontent.com/assets/6168860/7452680/19c38ef2-f237-11e4-8619-26f0f6bbb6db.png)

**Comment by peter1000** [comment]
**We could do that quite easily ourselves.** All we need is the source end line.

Something like this with a couple of different options to get a feeling  just click the source link: *seems nice doesn't it?*

---

**register!**(*modulename::Module, rootfile::AbstractString; args...*) &nbsp; &nbsp; [¶](https://github.com/MichaelHatherly/Docile.jl/issues/86) [[txt]](https://github.com/MichaelHatherly/Docile.jl/blob/master/src/Experimental/Cache/storage.jl#L67)[[src]](https://github.com/MichaelHatherly/Docile.jl/blob/master/src/Experimental/Cache/storage.jl#L85-L89)

[¶] (https://github.com/MichaelHatherly/Docile.jl/issues/86) &nbsp; &nbsp;**register!**(*modulename::Module, rootfile::AbstractString; args...*)  &nbsp; &nbsp; [[txt]](https://github.com/MichaelHatherly/Docile.jl/blob/master/src/Experimental/Cache/storage.jl#L67)[[src]](https://github.com/MichaelHatherly/Docile.jl/blob/master/src/Experimental/Cache/storage.jl#L85-L89)

[§](https://github.com/MichaelHatherly/Docile.jl/issues/86) &nbsp; &nbsp;  **register!**(*modulename::Module, rootfile::AbstractString; args...*)  &nbsp; &nbsp; [[txt]](https://github.com/MichaelHatherly/Docile.jl/blob/master/src/Experimental/Cache/storage.jl#L67)[[src]](https://github.com/MichaelHatherly/Docile.jl/blob/master/src/Experimental/Cache/storage.jl#L85-L89)

[[-]](https://github.com/MichaelHatherly/Docile.jl/issues/86) &nbsp; &nbsp;  **register!**(*modulename::Module, rootfile::AbstractString; args...*)  &nbsp; &nbsp; [[txt]](https://github.com/MichaelHatherly/Docile.jl/blob/master/src/Experimental/Cache/storage.jl#L67)[[src]](https://github.com/MichaelHatherly/Docile.jl/blob/master/src/Experimental/Cache/storage.jl#L85-L89)

**Comment by peter1000** [comment]
One other thing which might be helpful is to get the Permalink to display only when one hoovers over it like python or github uses it.

![untitled1](https://cloud.githubusercontent.com/assets/6168860/7453146/99c69702-f23c-11e4-9076-c350a19ff74f.png)
![untitled2](https://cloud.githubusercontent.com/assets/6168860/7453148/9b8661bc-f23c-11e4-9d14-58b1c6f558cc.png)

**Comment by MichaelHatherly** [comment]
> I think a requirement would be that it is exact otherwise it is better not to have such - at least I would find it a bit annoying ;)

Yes, having the wrong things is much worse than having nothing at all.

The Rust Docs are really quite nice I think.

**Comment by peter1000** [comment]
> The Rust Docs are really quite nice I think.

I don't think they base it on Markdown - but I believe we can improve adn the new Docile looks quite exciting. Seems also faster to me -but probably it's better to wait till finished to say so.

**Comment by MichaelHatherly** [comment]
> Seems also faster to me

Might be due to only loading docs when they're actually requested rather than all at once at the start.

**Comment by MichaelHatherly** [comment]
We're storing the start line as well now so the only action still needed is on the Lexicon side. Closing.
