### ISSUE TITLE
Asking for help!! peter1000

### ISSUE THREAD

**Issue by peter1000** [MichaelHatherly/Docile.jl#88]
hi 

If it is ok with you - I will use this here to ask for help if I get somewhere stuck related to Docile.

**Comment by peter1000** [comment]
##### HELP needed: fix for transfroms expr

Code branch is [here](https://github.com/peter1000/Docile.jl/tree/help_needed__fix_for_transfroms_expr)


example docstring I use is:
```
@doc "function `myrehash` with paramter types." ->
function myrehash_doc{K,V}(h::Dict{K,V}, k::ByteString, newsz=length(h.keys), x::Dict{K,V}=Dict([(:con, 10)]); 
                                            rm::Bool=false, prifix_ext::Dict{K,V}=Dict([(:remote, false)]))
end
```

----
* I added a small code [extract loop](https://github.com/peter1000/Docile.jl/blob/help_needed__fix_for_transfroms_expr/src/macros.jl#L257)

* My problem is this: if I run the loop [here](https://github.com/peter1000/Docile.jl/blob/help_needed__fix_for_transfroms_expr/src/macros.jl#L300) everything is as expected.

But after the [part below](https://github.com/peter1000/Docile.jl/blob/help_needed__fix_for_transfroms_expr/src/macros.jl#L308)
```
esc(:($autodocs; $oset; $obj; Docile.setmeta!(current_module(), $nset, :method, $source, $code, $(data...)); $n))
```

I get a problem in [Docile.setmeta!](https://github.com/peter1000/Docile.jl/blob/help_needed__fix_for_transfroms_expr/src/types.jl#L159) runing the same code extract method.


```
::::::::::: 2 :: setmeta!: Function  myrehash_doc


>>> 1 <<< extract_code_expr__code: Function  myrehash_doc
myrehash_doc

    dump(code): nothing


ERROR: LoadError: LoadError: type Function has no field args
 in extract_code_expr at /home/workerm/.julia/v0.4/Docile/src/macros.jl:261
```

QUESTION: Do you know how I can pass the [code](https://github.com/peter1000/Docile.jl/blob/help_needed__fix_for_transfroms_expr/src/macros.jl#L299) from here through without it being somehow transformed?

**Comment by MichaelHatherly** [comment]
> I found one possible way but I'm not sure if this is correct: seems to work.

Yes, you need to quote the code block if it's coming from a macro otherwise it will be spliced into the macro call site as code rather than expressions.

(Apologies for the slow response.)

**Comment by peter1000** [comment]
thanks I updated the PR I think that's it for the Docile side.

**Comment by peter1000** [comment]
Code question:

```
convert{T<:Tuple{Any,Vararg{Any}}}(::Type{T}, x::Tuple{Any, Vararg{Any}}) =
    tuple(convert(tuple_type_head(T),x[1]), convert(tuple_type_tail(T), tail(x))...)

```

the first arg `::Type{T}`  what does that do without any assigned name(symbol). Is it just a kind of placeholder: I saw one or two in your original Lexicon code for `mime::MIME"text/md"` there where some just `::MIME"text/html"`. does that assign to an autogenerated name or so?

**Comment by MichaelHatherly** [comment]
> does that assign to an autogenerated name or so?

Yes, below we get `#s4` which is what a `gensym` looks like:

```
julia> f{T}(::Type{T}) = T
f (generic function with 1 method)

julia> code_lowered(f, Tuple{Type{Int}})
1-element Array{Any,1}:
 :($(Expr(:lambda, Any[symbol("#s4")], Any[Any[],Any[Any[symbol("#s4"),:Any,0]],Any[],0], :(begin  # none, line 1:
        return T
    end::Any))))
```

They're placeholders, but since Julia is dispatch-oriented the "placeholders" definitely have an affect on behaviour.

**Comment by peter1000** [comment]
Question: ObjectIdDict

I see you are using quite often `ObjectIdDict`

Why is that need in Dociles case? did not fine to much info in the docs. In case it is included in userimg.jl ? Or any other reason ?

```
Alternatively, you can use the ObjectIdDict dictionary type, which is specially handled by precompilation so that it is safe to initialize at compile-time.
```

**Comment by MichaelHatherly** [comment]
Precompilation is the reason.

**Comment by peter1000** [comment]
Question: Scope: best way to handle return values from try/catch or for loops 

I sometimes wonder what is the best way to handle return values from lets say a try/catch part.

ACTUAL case: https://github.com/MichaelHatherly/Docile.jl/issues/94#issuecomment-98964257

```
 We should probably put a try-catch around parse in parsefile and return an empty Expr when it fails. 
```

[Current code](https://github.com/MichaelHatherly/Docile.jl/blob/master/src/Experimental/Utilities.jl#L16-L20)

```
function parsefile(file)
    text   = readall(file)
    result = parse("begin $(text) end")
    isexpr(result, :incomplete) ? parse(text) : result
end
```

How do you normally handle best this cases - this fails of course with `ERROR: LoadError: UndefVarError: result not defined`

```
function parsefile(file)
    text   = readall(file)
    try
        result = parse("begin $(text) end")
    catch 
        result = :()
    end
    isexpr(result, :incomplete) ? parse(text) : result
end
```

I understand that the try/catch creates an inner scope but comming from python I sometimes wonder how to write it best: declare `result` at the top and init it with nothing or in our case an empty Expr?

Just wonder how you normally do it.

Probably some of my question might seem dumm but I think better ask than never learn. Thanks anyway appriciate it.

**Comment by peter1000** [comment]
[Dict constructure](http://julia.readthedocs.org/en/latest/stdlib/collections/?highlight=dict#Base.Dict): I see you use mostly the `Dict("A"=>1, "B"=>2)` instead of `Dict([("A", 1), ("B", 2)])`

**Question: Has that any reason or is it just habbit?**

---

In my short tests it seems that there are some speed and memory differences.

`Dict([("A", 1), ("B", 2)])` about *20-30% more memory* usage but *10% faster* than `Dict("A"=>1, "B"=>2)`

of course this is just construction a Dict with 100 keys in a for loop 50000 times and might not reflect real usage.

```
>>>>>TEST1 Dict([("A", 1), ("B", 2)])
elapsed time: 1.025750343 seconds (666 MB allocated, 3.28% gc time in 31 pauses with 0 full sweep)
elapsed time: 1.038661983 seconds (666 MB allocated, 3.55% gc time in 31 pauses with 0 full sweep)
elapsed time: 1.035041221 seconds (666 MB allocated, 3.35% gc time in 30 pauses with 0 full sweep)
elapsed time: 1.03691791 seconds (666 MB allocated, 3.34% gc time in 30 pauses with 0 full sweep)
elapsed time: 1.037677023 seconds (666 MB allocated, 3.47% gc time in 31 pauses with 0 full sweep)

>>>>>TEST2 Dict("A"=>1, "B"=>2)
elapsed time: 1.159169548 seconds (513 MB allocated, 2.51% gc time in 23 pauses with 0 full sweep)
elapsed time: 1.162400202 seconds (513 MB allocated, 2.76% gc time in 24 pauses with 0 full sweep)
elapsed time: 1.157913909 seconds (513 MB allocated, 2.54% gc time in 23 pauses with 0 full sweep)
elapsed time: 1.161653248 seconds (513 MB allocated, 2.68% gc time in 24 pauses with 0 full sweep)
elapsed time: 1.1597654 seconds (513 MB allocated, 2.54% gc time in 23 pauses with 0 full sweep)
```

**Comment by MichaelHatherly** [comment]
> How do you normally handle best this cases

You can declare the variable outside the `try` with `local result`.

> Has that any reason or is it just habbit?

The `=>` looks nicer and is easier to type. The timing differences are quite interesting though, but for the moment not something we should loose any sleep over :), right?

**Comment by peter1000** [comment]
I saw you always do an import in your tests:

https://github.com/MichaelHatherly/Docile.jl/blob/master/test/Collector/facts.jl#L3
```
import PlainDocs
```

https://github.com/MichaelHatherly/Docile.jl/blob/master/test/Extensions/facts.jl#L3

```
import ExtensionTests
import Docile: Cache, Formats
```

any reason why not `using ExtensionTests`

**Comment by MichaelHatherly** [comment]
I've recently started to prefer using `import` to avoid cluttering the namespace slightly and make it more clear where methods are coming from. It's mostly just an experiment, but I'm finding it alright to far. I'll see how it goes though...

**Comment by MichaelHatherly** [comment]
FYI @peter1000 I've created a gitter.im chat room which might be better for these kind of questions. https://gitter.im/MichaelHatherly/Docile.jl
