### ISSUE TITLE
DocileExperimental Roadmap

### ISSUE THREAD

**Issue by peter1000** [MichaelHatherly/Docile.jl#89]
Maybe best to keep most of the related start pains here.

Edit: add thread related info from other post reply by MichaelHatherly: https://github.com/MichaelHatherly/Docile.jl/issues/86#issuecomment-98519790

> I do not understand the new design but it seems it is radically different

Basically:

* Capture module info by finding the file info of methods and macros defined in a module. [here](https://github.com/MichaelHatherly/Docile.jl/blob/434f22edba8e55c6ae3423f38657161bf4c4aff1/src/Experimental/Collector/search.jl#L28)
* Put submodules together into packages. [here](https://github.com/MichaelHatherly/Docile.jl/blob/434f22edba8e55c6ae3423f38657161bf4c4aff1/src/Experimental/Collector/types.jl#L60)
* Use the file info to extract docstrings as in the current version. Just without loopdocs. [here](https://github.com/MichaelHatherly/Docile.jl/blob/434f22edba8e55c6ae3423f38657161bf4c4aff1/src/Experimental/Runner/lookup.jl#L10)
* Store raw docstrings and metadata in two ObjectIdDicts rather than special Entry types. [here](https://github.com/MichaelHatherly/Docile.jl/blob/434f22edba8e55c6ae3423f38657161bf4c4aff1/src/Experimental/Cache/types.jl#L6)
* Have a third ObjectIdDict to store the "parsed" form of all raw docstrings.
* Each documented module has a set of three ObjectIdDicts.

There's not a huge amount different, mostly just streamlining and avoiding hooking into include as is currently done.

**Comment by MichaelHatherly** [comment]
> Maybe best to keep most of the related start pains here.

Yeah, good idea.

> Question: in the README you say: No Entry objects. category is defined by a metadata field per object.

The dispatch based on `Entry{category}` where category is a `Symbol` works, but I've started to find it a bit too "cute".

Currently the `Cache` module defines:

- `getraw(::Module, object)`
- `getparsed(::Module, object)`,  automatically parses raw strings as needed.
- `getmeta(::Module, object)`

to get single docstrings and metadata as well as

- `getraw(::Module)`
- `getparsed(::Module)`
- `getmeta(::Module)`

to get the entire list of documented objects and their docstrings for a module.

There's also the equivalent `set*!` methods.

That should be enough to interact with all the cached documentation. When you have the `object`, `parsed docs` and `metadata` for all documented modules that should be everything Lexicon needs, I think.

**Comment by peter1000** [comment]
My setup: copied all from Experiemental to Docile folder and renamed DocileExperimental to Docile. (Maybe a separate branch would also not be bad)

```
 using Docile
```

Question: register!(modulename::Module, rootfile::AbstractString; args...)

* rootfile: is that always where the module is defined.?

**Comment by MichaelHatherly** [comment]
> Maybe a separate branch would also not be bad

Yes.

> is that always where the module is defined.

It's where `module MODULENAME ... end` is found. So for a package it would be `Pkg.dir("MODULENAME", "src", "MODULENAME.jl")`.

**Comment by peter1000** [comment]
Will you support straight away julia 4 markdown instead of the outdated separate package?

**Comment by MichaelHatherly** [comment]
We'll use the external package for now. There's still some differences between them that would need back porting.

**Comment by peter1000** [comment]
> We'll use the external package for now. 

than it should be added to the Experimental REQUIRE isn't it?

**Comment by MichaelHatherly** [comment]
I'll put together a REQUIRE once this work gets merged into actual `Docile`. For the moment it doesn't really need it.

**Comment by peter1000** [comment]
The docstrings for modules sem to be now "normal Comments" is that the case?

Previously it was: `A Module object can be documented using the same syntax as for Functions`

**Comment by peter1000** [comment]
Just a question: should there be a `compat.jl` in Experiemental or do you want to handle it in each file as you did  in [lookup.jl](https://github.com/MichaelHatherly/Docile.jl/blob/master/src/Experimental/Runner/lookup.jl#L245)

**Comment by MichaelHatherly** [comment]
> The docstrings for modules seem to be now normal Comments is that the case?

That's mostly just me testing whether different docstrings work. Documenting `Module`s still works in the same way as before. The `["..."]` in that and other files is just some extra docs for the file.

> Just a question: should there be a compat.jl

If we start getting lots of compats needed then yes, but for the moment they can just go in the current files.

**Comment by peter1000** [comment]
Comments: I like the new syntax: question: for multilines one uses tripple quotes or multiple strings like:
`["line 1", "line 2", [line 3"]

**Comment by MichaelHatherly** [comment]
Multiline asides are just:

```jl
["""
...
"""]
```

There's only ever one string in the `[...]`.

**Comment by peter1000** [comment]
Current Lexicon save function needs to be changed to account for added`root file` -  adding rootfile will break with the previous Lexicon

`register!(modulename::Module, rootfile::AbstractString; args...)`


current Lexicon save
` function save(file::AbstractString, modulename::Module, config::Config; args...)`

to

`function save(file::AbstractString, modulename::Module, rootfile::AbstractString, config::Config; args...)`   

args... will be used for `Config` args adjustments as well as to pass arguments to `register!` ?

Any thoughts or can we do it like that?

**Comment by MichaelHatherly** [comment]
`save`'s signature should be able remain as is. Internally we call `getmodule(modulename).rootfile` which gives us the rootfile for a particular module.

The `Config` and `args` for `save` shouldn't interact with the `args` / `metadata` for a module. It's just naming conflicts there, the `args` aren't related.

**Comment by peter1000** [comment]
Maybe just a dumm question: if we solve it: getmodule(modulename).rootfile why do you need argument  `rootfile` in the first place?

**Comment by MichaelHatherly** [comment]
`register!` needs to know where to start searching for files that *might* be included in a package. It's possible we could remove the need to specify it to `register!`, though it might lead to more complex internals for `search.jl`.

**Comment by MichaelHatherly** [comment]
My previous comment

> Internally we call `getmodule(modulename).rootfile` which gives us the rootfile for a particular module.

should have read

> In `save` we would then call `getmodule(modulename).rootfile` which gives us the rootfile for a particular module for use in Lexicon.

**Comment by peter1000** [comment]
Thanks. I will try later a bit to find my way around.
Cheers

**Comment by peter1000** [comment]
> In save we would then call getmodule(modulename).rootfile which gives us the rootfile for a particular module for use in Lexicon.

Are you sure this works: I need to pass to [register!](https://github.com/MichaelHatherly/Docile.jl/blob/master/src/Experimental/Cache/storage.jl#L77)
the `rootfile`

but if I do: `rootfile = Docile.Cache.getmodule(modname)` it complains that

```
ERROR: LoadError: ArgumentError: No module 'Lexicon' currently cached.
 in getmodule at /home/workerm/.julia/v0.4/Docile/src/Cache/storage.jl:23
```

Maybe I did something wrong otherwise I think that it needs first to register the module and after that one can use `getmodule(modname)`

**Comment by peter1000** [comment]
Just something I came across: I forgot to change your path

```
julia> include("Docile.jl")

julia> Docile.Cache.register!(
           Docile,
           "/home/mike/.julia/v0.4/Docile/src//Docile.jl";
           format = Docile.Formats.PlaintextFormatter
       )
INFO: Registered package 'Docile'.

julia> Docile.Cache.getraw(Docile.Cache)
ERROR: SystemError: unable to read directory /home/mike/.julia/v0.4/Docile/src: No such file or directory

```

Maybe it should already check in `register!` if this is valid the output **INFO: Registered package 'Docile'.** seems a bit misleading with the later error.

Just a thought.

**Comment by peter1000** [comment]
I like your check points :+1: 

![screenshot from 2015-05-03 21-49-01](https://cloud.githubusercontent.com/assets/6168860/7447786/71e01690-f1de-11e4-826d-feb7c657952c.png)

**Comment by peter1000** [comment]
README:

seems that if I try to get a other module e.x Lexicon the README is not correct.

```
julia> # Get the raw docstrings from the `Cache` module.
       Docile.Cache.getraw(Lexicon.Cache)
ERROR: UndefVarError: Cache not defined

```

When I do it normally: it's ok
```
julia> # Get the raw docstrings from the `Cache` module.
       Docile.Cache.getraw(Lexicon)
INFO: Initialising cache for 'Lexicon' and related modules...
 Lexicon ✓
INFO: Succcessfully initialised package cache.

```

**Comment by peter1000** [comment]
README: just pointing out some issues I had - others might have similar

I first thought I do not have to import the module I want to document - I did it like this.

Wanted to document Lexicon:

```
julia> using Docile

julia> # Register a package by specifying a root module and file. Use `PlaintextFormatter`.
       Docile.Cache.register!(
           Lexicon,
           "/home/workerm/.julia/v0.4/Lexicon/src/Lexicon.jl";
           format = Docile.Formats.PlaintextFormatter
       )
ERROR: UndefVarError: Lexicon not defined

```

Just an misunderstand on my side - but maybe put it in the README.

**Comment by peter1000** [comment]
The register of the Markdown format [did not work](https://github.com/peter1000/Lexicon.jl/blob/master/src/render/md.jl#L3) for me so far.. anyway will stop now.

```
INFO: Registered package 'Lexicon'.
ERROR: LoadError: KeyError: Markdown not found
 in call at /home/workerm/.julia/v0.4/Docile/src/Collector/types.jl:104
 in getpackage at /home/workerm/.julia/v0.4/Docile/src/Cache/storage.jl:37
 in initdocs! at /home/workerm/.julia/v0.4/Docile/src/Cache/storage.jl:94
 in getdocs at /home/workerm/.julia/v0.4/Docile/src/Cache/storage.jl:114
```

Mostly worked on the [Config](https://github.com/peter1000/Lexicon.jl/blob/master/src/docs/config.md)

**Comment by MichaelHatherly** [comment]
> The register of the Markdown format did not work for me so far.. anyway will stop now.

The `const` was just to give the modules shorter names. You also need to define a 

```jl
parsedocs(::Format{MarkdownFormatter}, raw, obj, mod) = ...
```

method and pass `format = MarkdownFormatter` to `register!`.

I've pushed some changes for the other problems you've run into. It'll probably be the weekend before I can continue with further changes.

**Comment by peter1000** [comment]
> I've pushed some changes for the other problems you've run into. I

**thanks**

Seems I got the Formatter working in the REPL. 

QUESTION: nor sure if makes sense but is it planned/possible to register the same Module and file with different Formats at the same time. (not that I needed it but just a thought)

**Comment by peter1000** [comment]
I think I'm basically set to start but everything back again.

Just to clarify the idea: All extractions of signatures ect. are supposed to be done straight away in Lexicon

*Docile provides* 

* `getmeta` defaults: (:category, :textsource, :codesource)
* `getparsed`

**Comment by MichaelHatherly** [comment]
> register the same Module and file with different Formats at the same time

The format selector searches up from the object's metadata through the module's and their parents and then finally package's metadata [here](https://github.com/MichaelHatherly/Docile.jl/blob/a6b38bede4fa135f0d3eba20b333fd18865a5e5f/src/Experimental/Cache/utilities.jl#L10). Should handles arbitrary metadata keys.

We can pass a metadata to a particular module with

```jl
register!(MyModule, "..."; MyModule = Dict(:format => MyCustomFormatter))
```

any keywords that match a module name capture the provided metadata for the module rather than package [here](https://github.com/MichaelHatherly/Docile.jl/blob/a6b38bede4fa135f0d3eba20b333fd18865a5e5f/src/Experimental/Collector/types.jl#L114). A little hacky currently.

There's no way to directly add metadata to a particular docstring yet.

**Comment by MichaelHatherly** [comment]
I've pushed 1fc6f0a0ffb7f9bdbd3a9d171f981c81d1095e88, which adds a first attempt to remove the `register!` function. Now any package that is imported with `using ...` or `require("...")` gets found and cached. Uses the `Base.package_list` that I just stumbled upon today.

It appears to work fine so far, though probably has a few kinks to smooth out.

```jl
julia> require(".julia/v0.4/Docile/src/Experimental/DocileExperimental.jl")

julia> using Roots

julia> DocileExperimental.Cache.getraw(Roots)

julia> using Lazy

julia> DocileExperimental.Cache.getraw(Lazy)
```

We'll still need a way for package authors to specify their own package metadata to Docile.

**Comment by peter1000** [comment]
> We'll still need a way for package authors to specify their own package metadata to Docile.

Don't understand this but it looks really nice - the Readme example workd straight away

**Comment by peter1000** [comment]
Question: I worked on the `Lexicon Extensible Metadata Syntax` and just thought.

What happens if someone declares an complete empty docstring: is that just skipped or do you think it is valid?

```julia
""
function example1()
end
```

**Comment by MichaelHatherly** [comment]
> What happens if someone declares an complete empty docstring

The empty docstring is captured as is. This could be checked for by just iterating over `getraw(::Module)`. These kind of things could probably be a better fit for an improved `Lexicon.doctest`.

> should extract as much as possible info and skip silently such mistakes

I'd rather just raise an error every time for unmatched brackets. Makes things more explicit regarding what's legal syntax. Once again, could have something in `Lexicon.doctest` that checks for this kind of error.

**Comment by MichaelHatherly** [comment]
Progress update:

`@doc`, `@document` and `@docstrings` ported across in 2d2fe7504a197c42f58df4930b8938adf28a9827 and 53553b732ba44a8e2b0fb93f0be784edb3f43342. Docstrings are stored per module, as with the current Docile behaviour, and once `getparsed` is called the docstrings and metadata are moved across to the cache in the `Cache` module.

**Comment by peter1000** [comment]
Thanks.

Anyway: what do you think can we close this issues:

*  better solution for save: rootfile #92   (seems you solved that quite nicely)
* Kind of a bug: unrealated .jl in folder #94   should be closed by: #97

**Comment by peter1000** [comment]
I will start on a demo Lexicon implementing some of the ideas I posted and what I have in mind.
Than we could have a look togehter what you think and the parts which ar approved could be ported to the *New Lexicon*. This will take me probably a couple of days.

**Comment by MichaelHatherly** [comment]
> I will start on a demo Lexicon implementing some of the ideas

Sounds good.

I'm going to have a crack at getting `Interface` to be backwards compatible with Docile. (Not sure how possible that is though.)

Separating things into different modules like has been done here might be worth looking into for Lexicon. Such as `Lexicon.Doctest`, `Lexicon.Query`, `Lexicon.Render`, etc.

**Comment by peter1000** [comment]
I notice the module changes in docile

>I'm going to have a crack at getting Interface

I think for my demo Lexicon I'm just fine at the moment with what Docile provides so far.
Maybe the idea of reading an optional .docile file automatically if present would be of create help though.

**Comment by MichaelHatherly** [comment]
> what Docile provides so far

Did you mean DocileExperimental?

> optional .docile file

Yeah, I'll look into that today perhaps.

**Comment by peter1000** [comment]
> Did you mean DocileExperimental?

yes I renamed `DocileExperimental` to Docile for me. As long as there is no Taged release I think the couple of people who use it would not mind if master is `unstable` but improves at lightning speed.

Actually in the couple of weeks there was real nice changes ` the new docile` of yours is a great improvement.

**Comment by peter1000** [comment]
>> I will start on a demo Lexicon implementing some of the ideas

> Sounds good.


[Start a rough sketch of *Lexicon Experimental*](https://github.com/peter1000/Lexicon.jl)

I added some kind of Roadmap and went through most relevant issues on Docile/Lexicon.

This will take me some time: will still ask if I run in related issues ;)

**Comment by peter1000** [comment]
Case Idea/Question:

Sometimes one uses a longer docstring: like the Lexicon `save` uses.

Currently we have the `file"docs/save.md"` which is changed in the DoxileExperiment to: I think I undersood it like this `"docs/save.md"`.

**Question:**
I never liked the one for [Config](http://lexiconjl.readthedocs.org/en/latest/api/Lexicon/#type__config.1) too much because it created a very long entry which in my opinion  disrupts a bit the flow. It was even worth when we had all below the `save` method.

Anyway: In the future with a more flexible Section System I think such an long entry might deserve a separate output file without necessarily become a separate module. (assume we have all below the `save` function.

Options:

#### Manual page

Write a manual page for `save.md` and at the function a link to it. Because we still want to have the function an docstring so it shows up with the rest of it and also in the index.

Something like:

* Save the small  docstring with all other methods in: **Lexicon.md** > Exported > Methods > 1. item below the header

* Save the long  docstring in an other file: **Details.md** > Exported > Methods >  5. item below the header

```julia
"""
Saves the module documentation to file.

[Extended documentation](manual/save.md)  

!!section(Lexicon.md/Exported/Methods/1)      # only the small info to Exported/Methods

# in save.md define a !!section(Details.md/Exported/Methods/5)
"""
function save()end

```

? Does the DocileExperimental extract our `!!metadata() also from such manual pages?

#### Find other solution

Don't have an anwser yet that's why I ask what you think?

**Comment by peter1000** [comment]
Something else just came to mind: seeing the note above:

> \# in save.md define a !!section(Details.md/Exported/Methods/5)

Out of the box it produces:
```
Saves the module documentation to file.

[Extended documentation](manual/save.md)  

Lexicon.md/Exported/Methods/1      # only the small info to Exported/Methods

# in save.md define a Details.md/Exported/Methods/5
```
What if one wants to write an example explaining the usage of such metadata but they should not get replaced? Needs to write a new `function Formats.metamacro` isn't it or more complex?

Anyway - maybe such could functionality could be added to Docile or some better ways to keep it as is `\!!author(Michael Hatherly)`  will be kept as is?

```
"""
Metadata are a cool feature.

For Example \!!author(Michael Hatherly) will be by default expanded to 
**!!author(Michael Hatherly) **
"""
```
just a thought

**Comment by MichaelHatherly** [comment]
> What if one wants to write an example explaining the usage of such metadata but they should not get replaced?

Yeah, I probably should have added escaping to `!!` when I wrote it. Should definitely have that.

I'm not total clear on your other question though. It seems to mostly be a Lexicon issue?

In a `metamacro` we can get the current file which we can then use to stitch together multiple external documents with `readall`. Using `isinteractive()` in the `metamacro` we can decide whether a `!!` includes anything or not for interactive use at the REPL.

```jl
function Formats.metamacro(::MetaMacro{:longdescription}, body, mod, obj)
    dir = dirname(getmeta(mod, obj)[:textsouce][2])
    text = readall(joinpath(dir, body))
    isinteractive() ? "See manual for further details." : text
end
```

So if you read the REPL docs for

```jl
"""
...
!!longdescription(../docs/foobar.md)
...
"""
foobar(x) = x
```

then you'd get something like

```
...
See manual for further details.
...
```

But when you generate docs from the command line `isinteractive() == false` so you'd get:

```
...
<Really long descriptions goes here...>
...
```

Is this the kind of thing you were asking about?

**Comment by peter1000** [comment]
I'm not sure to be honest ;) I will open an Issue and when I have a better situation (or workable example I will ping you there?

**Comment by MichaelHatherly** [comment]
`.docile` config file has been implemented in 0af1b2c254d7502c25b711b04c55e517f5fb1239. Allows us to define `metamacro`s and custom docstring formatters for `parsedocs` and well as pass arbitrary `Dict{Symbol, Any}` to the package and it's modules.

**Comment by MichaelHatherly** [comment]
`Interface` translation layer and accompanying changes in f982641c3dd7a6fe8b9f7d572e08026502cc11ae.

**Comment by peter1000** [comment]
thanks. seems to next useful would be the escape for the `!!meta()` - maybe it's a quick one?

**Comment by MichaelHatherly** [comment]
I'm just tracking down a `ERROR: UndefVarError: @init not defined` error due to incorrect files being found for a module. If you'd like to give the `!!` escaping a try then go for it, or I'll do that after I've resolved this one.

**Comment by peter1000** [comment]
QUESTION: just a quick thought related to: **Extract for ALL Pkg documentation**

if one wants to extract lets say docs for 3 packages: Lexicon, Docile (incl  Docile submodules) and one other package).

Is there a way to associate metadata with the whole action instead of individual mudles.

I think you mention something like that somewhere but I can't find it - or maybe I'm mistaken.

**Comment by MichaelHatherly** [comment]
> Is there a way to associate metadata with the whole action instead of individual mudles.

There isn't currently. Probably doable on the Lexicon side though.

Something like

```jl
type MultiPackage
    packages :: Dict{Module, PackageData}
    metadata :: Dict{Symbol, Any}
end
```

might be enough.

**Comment by MichaelHatherly** [comment]
That `ERROR: UndefVarError: @init not defined` error should be resolved by 5d9e063765997ace83b5b44b29532ec823ff0c67.

**Comment by MichaelHatherly** [comment]
The trouble with `\!!` escaping is that the `\` isn't kept in the string

```
julia> "\!!"
"!!"
```

We need to do `\\!!` instead. Thoughts? It's not likely to be a heavily used feature, so probably alright to require the double `\` char.

**Comment by peter1000** [comment]
I think double `\\!!` is just fine: as you said it want be used much probably mostly in Docile's own documentation but it should be still be available.

Properly better than using some othe escape chars: the only one I could think of would be a tripple `!!!` for a *!* not

**Comment by MichaelHatherly** [comment]
> the only one I could think of would be a tripple `!!!` for a *!* not

Ha, good one :)

Bit more visually distinctive to have `\\!!` rather than `!!!` though.

Are you planning to implement? Should only need a minor change to https://github.com/MichaelHatherly/Docile.jl/blob/5d9e063765997ace83b5b44b29532ec823ff0c67/src/Experimental/Formats/metaparse.jl#L36 and surroundings.

**Comment by peter1000** [comment]
> Are you planning to implement?

I can give it a try later.

**Comment by peter1000** [comment]
I think I did it - will write a couple of tests and send the PR

**Comment by MichaelHatherly** [comment]
Thanks for bringing up tests @peter1000, I guess I should write some too :)

My thinking is to mirror the module structure for the tests dir:

```
test/
    TestPackage/
        src/
        ...
    Collector/
        facts.jl
        ...
    Cache/
    ...
    runtests.jl
```

Use the usual `context` `do`-blocks to separate different groups of tests per `facts.jl` file. `TestPackage` would mirror a typical Julian package structure.

**Comment by MichaelHatherly** [comment]
@peter1000, if you happen to be running into problems getting the tests organised (like a have for the last half hour) then feel free to submit without. We can add then once I switch over the code bases.

I've mostly got it working locally, `using Lexicon` and `?` work without any changes to the package which is great.

**Comment by peter1000** [comment]
Multi line metasyntax: do we want default skip extra produced emty lines?

At the moment:

```
"""
example5: Muli lines section meta: 
!!fields(

* `x`: point
* `y`: point

)
some more text

"""
```

will produce

```
"""
example5: Muli lines section meta: 
* `x`: point
* `y`: point
some more text
"""
```

Should that be the default? I do not have any real opinion but think if the coder but the extra line in the first place naybe he wants to keep them?

**Comment by peter1000** [comment]
Question: writing some tests I came across this thought:

What should be happening if there is a metasyntax within a metatext?

```julia
"""
"example8: meta within meta: !!multimeta(here is another meta: !!inner(This is the inner meta!))"
function example8() end
"""
```

currently I get the outer replaced the iner kept?

```
"example8: meta within meta: here is another meta: !!inner(This is the inner meta!)"
```

**Comment by peter1000** [comment]
Problem metaextraction: currently

```julia
"""
!!site_author(Michael Hatherly)
!!copyright((c) Michael Hatherly and other contributors.)

"""
function example_problem() end
```

results in
```
!!site_author(Michael Hatherly)
(c) Michael Hatherly and other contributors.

```

Which is not ok in my opinion.

**Comment by peter1000** [comment]
> https://github.com/MichaelHatherly/Docile.jl/issues/89#issuecomment-100545724
> if you happen to be running into problems getting the tests organised (like a have for the last half hour) then feel free to submit without. We can add then once I switch over the code bases.

I anyway renamed it for me and use only the new one. Added 14 basic metadata tests cases.

```
julia> Pkg.test("Docile")
INFO: Computing test dependencies for Docile...
INFO: No packages to install, update or remove
INFO: Testing Docile
ExampleMeta1.
     - Check getparsed metadata replacement.
INFO: Updating cached package list...
INFO: Initialising cache for 'ExampleMeta1' and related modules...
 ExampleMeta1 ✓
INFO: Succcessfully initialised package cache.
14 facts verified.
INFO: Docile tests passed
```

**Comment by peter1000** [comment]
> problems getting the tests organised (like a have for the last half hour)

I suggest to move the Experimental folder out of the old `src` I will do that with my PR.

**Comment by peter1000** [comment]
unrelated info: I saw you changed MkDocs profiles to: `flatly` this has a top banner so depending on the mdstyle you use you might need to add an extra css file.= for the permalinks and index to jump correctly.  When I do the new Lexicon examples I will add one such.

**Comment by peter1000** [comment]
I hope this is fine with you: #100 

Anyway above are a couple of comments which might need some decision: and related to the PR starting with here: https://github.com/MichaelHatherly/Docile.jl/issues/89#issuecomment-100528861

**Comment by MichaelHatherly** [comment]
> do we want default skip extra produced emty lines?

I think for the moment lets leave the behaviour as is. One can always add additional whitespace in a `metamacro`, but you wouldn't be able to remove extra whitespace once it's been added by `extractmeta` and friends. 

> What should be happening if there is a metasyntax within a metatext?

For the moment I think we should ignore nested `!!` syntax and just treat it as plaintext. If we start to need it we can add it then. Nested `\\!!` is even more of an edgecase, so we can address it later. 

> if we need more exceptions we could have a Set but at the moment I leave it like that.

For the moment it's fine with your change.

> I saw you changed MkDocs profiles to: `flatly`

Yeah, was just playing around with themes, but readthedocs seems to be ignoring my changes at the moment. Once we've got the Docile replaced with DocileExperimental we can address that one.

**Comment by peter1000** [comment]
>>  What should be happening if there is a metasyntax within a metatext?

> For the moment I think we should ignore nested !! syntax and just treat it as plaintext. If we start to need it we can add it then. Nested \\!! is even more of an edgecase, so we can address it later. 

This came up when I prepared the tests: just you know how? [part](https://github.com/MichaelHatherly/Docile.jl/blob/master/Experimental/test/Formats/ExampleMeta1.jl#L48-L50)

```julia
"""
!!site_author(Michael Hatherly)
!!copyright((c) Michael Hatherly and other contributors.)
!!license([MIT](https://github.com/MichaelHatherly/Lexicon.jl/blob/master/LICENSE.md))
"""

```

I thought to repeat your name in copyright automatically: something like a variable

```julia
"""
!!site_author(Michael Hatherly)
!!copyright((c) !!site_author() and other contributors.)
!!license([MIT](https://github.com/MichaelHatherly/Lexicon.jl/blob/master/LICENSE.md))
"""

```

I know you probably want change your name very often but for a more template  oriented way this would be maybe not too bad. Example:

```julia
"""
!!site_name( Docile.jl)
!!repo_url(https://github.com/MichaelHatherly/!!site_name())
!!license([MIT](https://github.com/MichaelHatherly/!!site_name()/blob/master/LICENSE.md))
"""
```

For github one would only need to care to change the`site_name` to a different one.

**Comment by peter1000** [comment]
Something else I thought this morning: do you think in Lexicon there whould be a separation of folder structure which define internal things like the REPL integration (which most people want change or add much extra code) and the part which is used for generation of standalone documentation. (which people might probably more easily add changes too)
Or with the new way Docile works one could also split it in separate pkgs.

 
In my opinion the Docile documentation should anyway be a multi-pkg one including Lexicon too.

e.g. create a `julia-documentation` organisation could hold one overall joined doc. Docile/Lexicon is a perfect example what the new of `julia-documentation` is:

split larger projects into smaller packages and create multi-pkg documentations for the whole project/organsation. 

---

That is why I asked and think **Docile** should has such feature integrated like [project-meta](https://github.com/MichaelHatherly/Docile.jl/issues/89#issuecomment-100464066).

Lexicon can do that but I would think as Docile provides the other metadata things it might be better to have one there (nothing fancy but something like: `multi-pkg metadata` or `project_meta`

**Comment by MichaelHatherly** [comment]
> do you think in Lexicon there whould be a separation of folder structure which define internal things like the REPL integration

That's the idea.

> Or with the new way Docile works one could also split it in separate pkgs.

I'm not planning to do any more package splitting for the foreseeable future. If there *really* turns out to be a need we *could* think about it, but I've not thought there is.

> In my opinion the Docile documentation should anyway be a multi-pkg one including Lexicon too.

There's been discussion in the past about this. Until package pre-compilation is in `stable` the extra time needed to import `Markdown` was annoying for documenting a package with `using Docile`. Once `@document` and `@docstrings` style on documenting is phased out we can think more concretely about this one.

**Comment by MichaelHatherly** [comment]
Since we've now switched over I'm going to close this issue. Of course sub-issues that remain can be split out into separate issues of their own now.
