### ISSUE TITLE
Better github code reference.

### ISSUE THREAD

**Issue by peter1000** [MichaelHatherly/Docile.jl#90]
---

##### Better github code reference: inspired by this [comment](https://github.com/MichaelHatherly/Docile.jl/issues/86#issuecomment-98686320)

Probably we have all except the code endline: anyway here it is what I think we have to watch out for.

* needs exact line numbers for: `docstring startline, endline`
* needs exact line numbers for: `code startline, endline`

MAIN ISSUES: To watch out if there are empty lines or commend lines between docstring end and code start lines

**txt_startln**: Must be the start line of the single/tripple quoted docstring or aside open bracket in case it goes over multiple lines

**txt_endln**: Must be the end line of the single/tripple quoted docstring or aside end bracket 

**code_startln**: Must be the actual code start disregarding any empty or commentlines between docstring and code

**code_endln**: Must be the actual end line of the code: e.g for a function the last `end`

```
"""  #txt_startln
our nice documentation function

""" #txt_endln


# some funny empty and comment lines added by the coder
# this could happen eventhough it should not.

function nice_documentation() #code_startln
    txt_startln = 123
    txt_endln = 138
    code_startln = 145
    code_endln = 163

end #code_endln
```

If we have that we have all options for instance to reference the whole block line form `txt_startln - code_endln` or the split txt, code option.

**Comment by MichaelHatherly** [comment]
Could do, might be possible to do this from the Lexicon side completely since we'll have stored the file paths and it might be easier to find endings in the text source rather than parsed `Expr`s.

**Comment by MichaelHatherly** [comment]
As much line info as needed is now being stored in metadata. The rest of the concerns here can be met in Lexicon.
