### ISSUE TITLE
better solution for save: rootfile

### ISSUE THREAD

**Issue by peter1000** [MichaelHatherly/Docile.jl#92]
[comment](https://github.com/MichaelHatherly/Docile.jl/issues/89#issuecomment-98558632)

Temporar workaround

```
function save(file::AbstractString, modname::Module, config::Config; args...)
    config = update_config!(deepcopy(config), Dict(args))
    mime = MIME("text/$(strip(last(splitext(file)), '.'))")

    # `rootfile` is where module `modname ... end` is found. 
    # So for a package it would be `Pkg.dir("MODULENAME", "src", "MODULENAME.jl")`.
    modname_str = string(modname)
    rootfile = Pkg.dir(modname_str, "src", "$(modname_str).jl")
    .........
end
```

but what about if a file defines 2 modules which do not both reflect the `.jl` name?

**Comment by MichaelHatherly** [comment]
Should just need `rootfile = getmodule(modname).rootfile` unless I'm missing something.

**Comment by peter1000** [comment]
related: https://github.com/MichaelHatherly/Docile.jl/issues/89#issuecomment-98829960
