### ISSUE TITLE
Git marks package as dirty on case insensitive filesystems

### ISSUE THREAD

**Issue by ncnc** [MichaelHatherly/Docile.jl#98]
The files `formats.jl` and `Formats.jl` (in `Experimental/Formats`) confuse git on machines with case insensitive filesystems and consequently marks the package as permanently dirty.

Renaming one of the files should fix the problem.

**Comment by MichaelHatherly** [comment]
:( oh... well that's annoying. Thanks for pointing it out @ncnc. Is the only solution to just rename the files?

**Comment by MichaelHatherly** [comment]
Changed in a9e6daf022c11f3e384f962dd40670bdaae18216 and 71f055623d6fe43b365e9e20036639ee49f5e23e.

**Comment by ncnc** [comment]
Thanks! I had to clone master manually, but now it seems ok.

I'm not aware of any other workarounds.

**Comment by MichaelHatherly** [comment]
Tagged version 0.4.13, https://github.com/JuliaLang/METADATA.jl/pull/2571, with this fix.
